### ISSUE TITLE
execsnoop.bt fails verifier check (R1 !read_ok)

### ISSUE THREAD

**Issue by daniel-thompson** [iovisor/bpftrace#2249] opened 2022-05-30 13:22 UTC
### What reproduces the bug?

```
holly$ sudo bpftrace /usr/share/bpftrace/tools/execsnoop.bt 
Attaching 3 probes...
ERROR: Error loading program: tracepoint:syscalls:sys_enter_execve (try -v)
bpftrace /usr/share/bpftrace/tools/execsnoop.bt
```

Re-run with -v we get:

```
holly$ sudo /home/drt/Apps/bpftrace-git-x86_64/bin/bpftrace -v /usr/share/bpftrace/tools/execsnoop.bt 
INFO: node count: 23
Attaching 3 probes...

Program ID: 140

The verifier log: 
processed 24 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

Attaching BEGIN

Error log: 
0: R1=ctx(id=0,off=0,imm=0) R10=fp0
0: (bf) r6 = r1                       ; R1=ctx(id=0,off=0,imm=0) R6_w=ctx(id=0,off=0,imm=0)
1: (b7) r1 = 1                        ; R1_w=inv1
2: (7b) *(u64 *)(r10 -40) = r1        ; R1_w=inv1 R10=fp0 fp-40_w=inv1
3: (b7) r7 = 0                        ; R7_w=inv0
4: (7b) *(u64 *)(r10 -16) = r7        ; R7_w=invP0 R10=fp0 fp-16_w=00000000
5: (18) r1 = 0xffff9d3c75a8cc00       ; R1_w=map_ptr(id=0,off=0,ks=8,vs=8,imm=0)
7: (bf) r2 = r10                      ; R2_w=fp0 R10=fp0
8: (07) r2 += -16                     ; R2_w=fp-16
9: (85) call bpf_map_lookup_elem#1    ; R0_w=map_value_or_null(id=1,off=0,ks=8,vs=8,imm=0)
10: (b7) r8 = 0                       ; R8_w=inv0
11: (15) if r0 == 0x0 goto pc+1       ; R0_w=map_value(id=0,off=0,ks=8,vs=8,imm=0)
12: (79) r8 = *(u64 *)(r0 +0)         ; R0=map_value(id=0,off=0,ks=8,vs=8,imm=0) R8=inv(id=0)
13: (85) call bpf_ktime_get_boot_ns#125       ; R0_w=inv(id=0)
14: (1f) r0 -= r8                     ; R0_w=inv(id=0) R8=inv(id=0)
15: (37) r0 /= 1000000                ; R0_w=inv(id=0)
16: (7b) *(u64 *)(r10 -32) = r0       ; R0_w=inv(id=0) R10=fp0 fp-32_w=mmmmmmmm
17: (85) call bpf_get_current_pid_tgid#14     ; R0_w=inv(id=0)
18: (77) r0 >>= 32                    ; R0_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff))
19: (7b) *(u64 *)(r10 -24) = r0       ; R0_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0 fp-24_w=inv
20: (18) r2 = 0xffff9d3b46df2400      ; R2_w=map_ptr(id=0,off=0,ks=4,vs=4,imm=0)
22: (bf) r4 = r10                     ; R4_w=fp0 R10=fp0
23: (07) r4 += -40                    ; R4_w=fp-40
24: (bf) r1 = r6                      ; R1_w=ctx(id=0,off=0,imm=0) R6=ctx(id=0,off=0,imm=0)
25: (18) r3 = 0xffffffff              ; R3_w=inv4294967295
27: (b7) r5 = 24                      ; R5_w=inv24
28: (85) call bpf_perf_event_output#25        ; R0=inv(id=0)
29: (79) r8 = *(u64 *)(r6 +24)        ; R6=ctx(id=0,off=0,imm=0) R8_w=inv(id=0)
30: (63) *(u32 *)(r10 -4) = r7        ; R7=invP0 R10=fp0 fp-8=0000????
31: (18) r1 = 0xffff9d3b46df2000      ; R1_w=map_ptr(id=0,off=0,ks=4,vs=16400,imm=0)
33: (bf) r2 = r10                     ; R2_w=fp0 R10=fp0
34: (07) r2 += -4                     ; R2_w=fp-4
35: (85) call bpf_map_lookup_elem#1   ; R0_w=map_value_or_null(id=2,off=0,ks=4,vs=16400,imm=0)
36: (bf) r7 = r0                      ; R0_w=map_value_or_null(id=2,off=0,ks=4,vs=16400,imm=0) R7_w=map_value_or_null(id=2,off=0,ks=4,vs=16400,imm=0)
37: (55) if r7 != 0x0 goto pc+2 40: R0_w=map_value(id=0,off=0,ks=4,vs=16400,imm=0) R6=ctx(id=0,off=0,imm=0) R7_w=map_value(id=0,off=0,ks=4,vs=16400,imm=0) R8_w=inv(id=0) R10=fp0 fp-8=mmmm???? fp-16=mmmmmmmm fp-24=mmmmmmmm fp-32=mmmmmmmm fp-40=mmmmmmmm
40: (b7) r1 = 0                       ; R1_w=inv0
41: (7b) *(u64 *)(r7 +8) = r1         ; R1_w=inv0 R7_w=map_value(id=0,off=0,ks=4,vs=16400,imm=0)
42: (b7) r1 = 30005                   ; R1_w=inv30005
43: (7b) *(u64 *)(r7 +0) = r1         ; R1_w=inv30005 R7_w=map_value(id=0,off=0,ks=4,vs=16400,imm=0)
44: (bf) r1 = r10                     ; R1_w=fp0 R10=fp0
45: (07) r1 += -40                    ; R1_w=fp-40
46: (b7) r2 = 8                       ; R2_w=inv8
47: (bf) r3 = r8                      ; R3_w=inv(id=3) R8_w=inv(id=3)
48: (85) call bpf_probe_read_user#112         ; R0=inv(id=0) fp-40=mmmmmmmm
49: (79) r3 = *(u64 *)(r10 -40)       ; R3_w=inv(id=0) R10=fp0
50: (b7) r2 = 1024                    ; R2_w=inv1024
51: (85) call bpf_probe_read_user_str#114
R1 !read_ok
processed 48 insns (limit 1000000) max_states_per_insn 0 total_states 4 peak_states 4 mark_read 2

ERROR: Error loading program: tracepoint:syscalls:sys_enter_execve
```

### bpftrace --info

This specific --info below comes from Fedora 36/x86_64 + bpftrace from git. I have also observed the problem with:

* Fedoa 36/x86_64 with distro default bpftrace (v0.14.1)
* OpenEmbedded 4.0 (kirkstone)/aarch64 with default bpftrace (v0.14.0)

```
holly$ sudo bpftrace --info
System
  OS: Linux 5.17.11-300.fc36.x86_64 #1 SMP PREEMPT Wed May 25 15:04:05 UTC 2022
  Arch: x86_64

Build
  version: v0.15.0-12-g6f5bd
  LLVM: 14.0.0
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): yes
  map batch (depends on Build:libbpf): yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes

```

**Comment by viktormalik** [comment] 2022-05-31 06:39
This is a problem of LLVM 14 which has broken the `join` builtin. See #2222 for details.

**Comment by viktormalik** [comment] 2022-05-31 06:39
Closing as duplicate of #2222.

**Closed by viktormalik** 2022-05-31 06:39 UTC
Labels: bug
