### ISSUE TITLE
BEGIN probe cannot printf message

### ISSUE THREAD

**Issue by yujinqiu** [iovisor/bpftrace#218] opened 2018-10-26 04:41 UTC
Hi,  
I cannot get the BEGIN probe printf message

```
bpftrace -e 'BEGIN { printf("Hello, World!\n"); }'
Attaching 1 probe...
^C
```
"Hello, World!" message does not show up. 
For further investigation, I also  list the verbose info below. 

```
bpftrace  -v  -e 'BEGIN { printf("Hello, World!\n"); }'
Attaching 1 probe...

Bytecode:
0: (bf) r6 = r1
1: (b7) r1 = 0
2: (7b) *(u64 *)(r10 -8) = r1
3: (18) r7 = 0xffff88002f94b100
5: (85) call bpf_get_smp_processor_id#8
6: (bf) r4 = r10
7: (07) r4 += -8
8: (bf) r1 = r6
9: (bf) r2 = r7
10: (bf) r3 = r0
11: (b7) r5 = 8
12: (85) call bpf_perf_event_output#25
13: (b7) r0 = 0
14: (95) exit
processed 14 insns, stack depth 8

Attaching BEGIN
Running...
^C
```
```
bpftrace  -dd  -e 'BEGIN { printf("Hello, World!\n"); }'
Program
 BEGIN
  call: printf
   string: Hello, World!\n

Before optimization
-------------------

; ModuleID = 'bpftrace'
source_filename = "bpftrace"
target datalayout = "e-m:e-p:64:64-i64:64-n32:64-S128"
target triple = "bpf-pc-linux"

%printf_t = type { i64 }

; Function Attrs: nounwind
declare i64 @llvm.bpf.pseudo(i64, i64) #0

; Function Attrs: alwaysinline
define internal i64 @log2(i64) #1 section "helpers" {
entry:
  %1 = alloca i64
  %2 = alloca i64
  %3 = bitcast i64* %2 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %3)
  store i64 %0, i64* %2
  %4 = bitcast i64* %1 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %4)
  store i64 0, i64* %1
  %5 = load i64, i64* %2
  %6 = icmp sge i64 %5, 65536
  %7 = zext i1 %6 to i64
  %8 = shl i64 %7, 4
  %9 = lshr i64 %5, %8
  store i64 %9, i64* %2
  %10 = load i64, i64* %1
  %11 = add i64 %10, %8
  store i64 %11, i64* %1
  %12 = load i64, i64* %2
  %13 = icmp sge i64 %12, 256
  %14 = zext i1 %13 to i64
  %15 = shl i64 %14, 3
  %16 = lshr i64 %12, %15
  store i64 %16, i64* %2
  %17 = load i64, i64* %1
  %18 = add i64 %17, %15
  store i64 %18, i64* %1
  %19 = load i64, i64* %2
  %20 = icmp sge i64 %19, 16
  %21 = zext i1 %20 to i64
  %22 = shl i64 %21, 2
  %23 = lshr i64 %19, %22
  store i64 %23, i64* %2
  %24 = load i64, i64* %1
  %25 = add i64 %24, %22
  store i64 %25, i64* %1
  %26 = load i64, i64* %2
  %27 = icmp sge i64 %26, 4
  %28 = zext i1 %27 to i64
  %29 = shl i64 %28, 1
  %30 = lshr i64 %26, %29
  store i64 %30, i64* %2
  %31 = load i64, i64* %1
  %32 = add i64 %31, %29
  store i64 %32, i64* %1
  %33 = load i64, i64* %2
  %34 = icmp sge i64 %33, 2
  %35 = zext i1 %34 to i64
  %36 = shl i64 %35, 0
  %37 = lshr i64 %33, %36
  store i64 %37, i64* %2
  %38 = load i64, i64* %1
  %39 = add i64 %38, %36
  store i64 %39, i64* %1
  %40 = load i64, i64* %1
  ret i64 %40
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64, i8* nocapture) #2

; Function Attrs: alwaysinline
define internal i64 @linear(i64, i64, i64, i64) #1 section "helpers" {
entry:
  %4 = alloca i64
  %5 = alloca i64
  %6 = alloca i64
  %7 = alloca i64
  %8 = alloca i64
  %9 = bitcast i64* %8 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %9)
  %10 = bitcast i64* %7 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %10)
  %11 = bitcast i64* %6 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %11)
  %12 = bitcast i64* %5 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %12)
  %13 = bitcast i64* %4 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %13)
  store i64 %0, i64* %8
  store i64 %1, i64* %7
  store i64 %2, i64* %6
  store i64 %3, i64* %5
  %14 = load i64, i64* %7
  %15 = load i64, i64* %8
  %16 = icmp slt i64 %15, %14
  br i1 %16, label %lhist.lt_min, label %lhist.ge_min

lhist.lt_min:                                     ; preds = %entry
  ret i64 0

lhist.ge_min:                                     ; preds = %entry
  %17 = load i64, i64* %6
  %18 = load i64, i64* %8
  %19 = icmp sgt i64 %18, %17
  br i1 %19, label %lhist.gt_max, label %lhist.le_max

lhist.le_max:                                     ; preds = %lhist.ge_min
  %20 = load i64, i64* %5
  %21 = load i64, i64* %7
  %22 = load i64, i64* %8
  %23 = sub i64 %22, %21
  %24 = sdiv i64 %23, %20
  %25 = add i64 %24, 1
  store i64 %25, i64* %4
  %26 = load i64, i64* %4
  ret i64 %26

lhist.gt_max:                                     ; preds = %lhist.ge_min
  %27 = load i64, i64* %5
  %28 = load i64, i64* %7
  %29 = load i64, i64* %6
  %30 = sub i64 %29, %28
  %31 = sdiv i64 %30, %27
  %32 = add i64 %31, 1
  store i64 %32, i64* %4
  %33 = load i64, i64* %4
  ret i64 %33
}

define i64 @BEGIN(i8*) section "s_BEGIN_1" {
entry:
  %printf_args = alloca %printf_t
  %1 = bitcast %printf_t* %printf_args to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %1)
  %2 = bitcast %printf_t* %printf_args to i8*
  call void @llvm.memset.p0i8.i64(i8* %2, i8 0, i64 8, i32 1, i1 false)
  store i64 0, %printf_t* %printf_args
  %pseudo = call i64 @llvm.bpf.pseudo(i64 1, i64 1)
  %get_cpu_id = call i64 inttoptr (i64 8 to i64 ()*)()
  %perf_event_output = call i64 inttoptr (i64 25 to i64 (i8*, i8*, i64, i8*, i64)*)(i8* %0, i64 %pseudo, i64 %get_cpu_id, %printf_t* %printf_args, i64 8)
  %3 = bitcast %printf_t* %printf_args to i8*
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* %3)
  ret i64 0
}

; Function Attrs: argmemonly nounwind
declare void @llvm.memset.p0i8.i64(i8* nocapture writeonly, i8, i64, i32, i1) #2

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64, i8* nocapture) #2

attributes #0 = { nounwind }
attributes #1 = { alwaysinline }
attributes #2 = { argmemonly nounwind }

After optimization
------------------

; ModuleID = 'bpftrace'
source_filename = "bpftrace"
target datalayout = "e-m:e-p:64:64-i64:64-n32:64-S128"
target triple = "bpf-pc-linux"

%printf_t = type { i64 }

; Function Attrs: nounwind
declare i64 @llvm.bpf.pseudo(i64, i64) #0

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64, i8* nocapture) #1

define i64 @BEGIN(i8*) local_unnamed_addr section "s_BEGIN_1" {
entry:
  %printf_args = alloca %printf_t, align 8
  %1 = bitcast %printf_t* %printf_args to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* nonnull %1)
  store i64 0, %printf_t* %printf_args, align 8
  %pseudo = tail call i64 @llvm.bpf.pseudo(i64 1, i64 1)
  %get_cpu_id = tail call i64 inttoptr (i64 8 to i64 ()*)()
  %perf_event_output = call i64 inttoptr (i64 25 to i64 (i8*, i8*, i64, i8*, i64)*)(i8* %0, i64 %pseudo, i64 %get_cpu_id, %printf_t* nonnull %printf_args, i64 8)
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* nonnull %1)
  ret i64 0
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64, i8* nocapture) #1

attributes #0 = { nounwind }
attributes #1 = { argmemonly nounwind }
```

```
bpftrace loads.bt
Attaching 2 probes...
12:14:53 load averages: 0.119 0.053 0.008
12:14:54 load averages: 0.119 0.053 0.008
12:14:55 load averages: 0.119 0.053 0.008
^C
```
"Reading load averages... Hit Ctrl-C to end."  message does not show up too.

**Comment by mmarchini** [comment] 2018-10-27 14:03
Hi, thank you for sharing bytecode and IR outputs. Could you please also provide details about your environment? Especially LLVM/Clang versions, Kernel version, and distro name/version.

**Comment by yujinqiu** [comment] 2018-10-29 08:12
Hi  @yujinqiu  thank you for reply.  The bpftrace binary  was build from  Docker Image (Image ID: b5b4010cf744) followding the [doc](https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#using-docker) ,  

```
docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
bpftrace-builder               latest              b5b4010cf744        2 weeks ago         694 MB
```
and then  I  copy the bpftrace binary  to  CentOS Linux release 7.3.1611 (Core) with kernel version: 4.11.2.

**Comment by williangaspar** [comment] 2018-12-26 11:49
I replicated the behavior on my machine. It seems that the release executable is not calling BEGIN at all. 
The problem does not happen on debug mode `./build-debug.sh`

**Comment by mmarchini** [comment] 2019-01-14 18:12
@yujinqiu can you confirm if this issue is still present on the latest version? I just tested it here and it seems to be working now.

(FYI alpine build, and thus `./build.sh`, is not working right now due to #327)

**Comment by navytux** [comment] 2019-02-07 09:48
Debian just packaged bpftrace (https://packages.debian.org/sid/bpftrace) and the issue is present there:

```
# dpkg -l |grep bpf
ii  bpftrace                                      0.8+git60-gccac69c2239b-1                               amd64        high-level tracing language for Linux eBPF
ii  libbpfcc                                      0.8.0-4                                                 amd64        shared library for BPF Compiler Collection (BCC)
ii  libbpfcc-dev                                  0.8.0-4                                                 amd64        shared library for BPF Compiler Collection (BCC)

# bpftrace -e 'BEGIN { printf("Hello, World!\n"); }'
Attaching 1 probe...
^C
```

/cc @vincentbernat

**Comment by navytux** [comment] 2019-02-07 14:26
On the other hand, with latest bpftrace (v0.8-68-g90e5443) manually built against the same libbpfcc from Debian and standard LLVM-7 on Debian it works:

```
root@deco:/home/kirr/src/tools/bpf/bpftrace/build/src# ./bpftrace -e 'BEGIN { printf("Hello, World!\n"); }'
Attaching 1 probe...
Hello, World!
^C
```

**Comment by vincentbernat** [comment] 2019-02-07 15:08
Hum, there seems to be a variation in the build process. If I emit the exact same commands used for building the package with the same sources, I get a working `bpftrace` executable. There must be something subtle with the build environment. I'll investigate more.

**Comment by vincentbernat** [comment] 2019-02-07 15:38
Setting `CXXFLAGS` to `-O2` (`export CFLAGS=-O2`) is enough to trigger the bug. I can avoid using such a flag, but maybe it's hiding another bug?

**Comment by navytux** [comment] 2019-02-07 16:19
> Debian is compiled with gcc, should I use clang instead?

about this I can note that bpftrace travis builds are handled with gcc/g++, see e.g.:

https://github.com/iovisor/bpftrace/blob/master/.travis.yml
https://github.com/iovisor/bpftrace/blob/master/docker/Dockerfile.fedora29
https://github.com/iovisor/bpftrace/blob/master/docker/Dockerfile.fedora28
https://travis-ci.org/iovisor/bpftrace/jobs/490091897

**Comment by caringi** [comment] 2019-02-07 16:22
I can confirm the same behavior in my system:

- Fedora 29
- Kernel 4.20.4-200.fc29.x86_64
- bpftrace latest version from git
- llvm 7

If bpftrace is built with -DCMAKE_BUILD_TYPE=DEBUG (no optimization flags are used) the problem doesn't show up.

```
./bpftrace -e 'BEGIN { printf("Hello, World!\n"); }'
Attaching 1 probe...
Hello, World!
^C

```
Building bpftrace with -DCMAKE_BUILD_TYPE=RELWITHDEBINFO (which uses -O2 flag), the BEGIN probe doesn't work as expected:

```
./bpftrace -e 'BEGIN { printf("Hello, World!\n"); }'
Attaching 1 probe...
^C
```

**Comment by brendangregg** [comment] 2019-02-07 17:02
I can guess what's going on: BEGIN creates a dummy C function to trace with no contents, and the compiler is optimizing it away.

Either we need a compiler directive on that function, or to use -O0.

**Comment by vincentbernat** [comment] 2019-02-07 17:33
We could use `__attribute__((optimize("O0")))` or `__attribute__(used)`.

**Comment by brendangregg** [comment] 2019-02-07 19:38
Just fixed by @caringi, closing. #401 . @vincentbernat : if that build re-runs, it should work now.

**Closed by brendangregg** 2019-02-07 19:38 UTC
Labels: bug

**Comment by vincentbernat** [comment] 2019-02-07 19:55
Just applying this patch (9f2069b2210fc89274350af5d31533f9245d7361) works. I did not push the new release in Debian yet to ensure bpftrace reaches testing before the freeze. Once it's here, I will be able to upload it.

**Comment by navytux** [comment] 2019-02-08 08:15
@caringi, @brendangregg, may I suggest that the bug is not yet fully fixed: there is no test that covers it. I thus suggest to add to travis another mode that uses -O2 (or change Release to use it). Then we can be sure that the bug won't silently return and that there won't be other silent bugs related to -O2. Thanks.
