### ISSUE TITLE
undefined reference to symbol 'inflateEnd' while compile bpftrace.

### ISSUE THREAD

**Issue by wingfancy** [iovisor/bpftrace#1709] opened 2021-02-27 14:08 UTC
Any idea on how to fix this issue? Thanks in advance.

[ 34%] Built target watchpoint_unwatch
[ 35%] Built target simple
[ 36%] Built target uprobe_negative_retval
[ 37%] Performing build step for 'gtest-git'
[ 38%] Built target string_args
[ 57%] Built target man
[ 62%] Built target ast
[ 25%] Built target gtest
[ 50%] Built target gtest_main
[ 75%] Built target gmock
[ 63%] Linking CXX executable bpftrace
[100%] Built target gmock_main
[ 64%] Built target gtest-git-build
[ 64%] Linking CXX executable bpftrace_test
/usr/local/bin/ld: /usr/local/lib/libbfd.a(compress.o): undefined reference to symbol 'inflateEnd'
/usr/local/bin/ld: /lib/aarch64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/bpftrace.dir/build.make:470: src/bpftrace] Error 1
make[1]: *** [CMakeFiles/Makefile2:1202: src/CMakeFiles/bpftrace.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/local/bin/ld: /usr/local/lib/libbfd.a(compress.o): undefined reference to symbol 'inflateEnd'
/usr/local/bin/ld: /lib/aarch64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/bpftrace_test.dir/build.make:787: tests/bpftrace_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:1600: tests/CMakeFiles/bpftrace_test.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by fbs** [comment] 2021-02-27 16:51
Sounds like libz is not being linked in properly.

What os are you on? Can you add the full cmake output and maybe compile with `-DCMAKE_VERBOSE_MAKEFILE=1` to see the exact line on failure?

**Comment by wingfancy** [comment] 2021-02-28 01:12
Thanks for your help.
I'm build it on adeb(https://github.com/joelagnel/adeb), it's a debin system on Android device.
After I fixed the libz issue by addind it to the make file, I got the new issue below. May I get your help on this? Thanks in advnace.
```
cd /data/local/bpftrace/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/bpftrace.dir/link.txt --verbose=1
/usr/bin/clang++-7  -O3 -DNDEBUG   CMakeFiles/bpftrace.dir/attached_probe.cpp.o CMakeFiles/bpftrace.dir/bpffeature.cpp.o CMakeFiles/bpftrace.dir/bpftrace.cpp.o CMakeFiles/bpftrace.dir/btf.cpp.o CMakeFiles/bpftrace.dir/child.cpp.o CMakeFiles/bpftrace.dir/clang_parser.cpp.o CMakeFiles/bpftrace.dir/disasm.cpp.o CMakeFiles/bpftrace.dir/driver.cpp.o CMakeFiles/bpftrace.dir/fake_map.cpp.o CMakeFiles/bpftrace.dir/lockdown.cpp.o CMakeFiles/bpftrace.dir/log.cpp.o CMakeFiles/bpftrace.dir/map.cpp.o CMakeFiles/bpftrace.dir/mapkey.cpp.o CMakeFiles/bpftrace.dir/output.cpp.o CMakeFiles/bpftrace.dir/probe_matcher.cpp.o CMakeFiles/bpftrace.dir/procmon.cpp.o CMakeFiles/bpftrace.dir/printf.cpp.o CMakeFiles/bpftrace.dir/resolve_cgroupid.cpp.o CMakeFiles/bpftrace.dir/signal.cpp.o CMakeFiles/bpftrace.dir/struct.cpp.o CMakeFiles/bpftrace.dir/tracepoint_format_parser.cpp.o CMakeFiles/bpftrace.dir/types.cpp.o CMakeFiles/bpftrace.dir/usdt.cpp.o CMakeFiles/bpftrace.dir/utils.cpp.o CMakeFiles/bpftrace.dir/bfd-disasm.cpp.o CMakeFiles/bpftrace.dir/main.cpp.o  -o bpftrace /usr/local/lib/libbfd.a /usr/local/lib/libopcodes.a arch/libarch.a ast/libast.a ../libparser.a ../resources/libresources.a /usr/lib/aarch64-linux-gnu/libbcc.so /usr/lib/aarch64-linux-gnu/libelf.so -lz -lstdc++fs arch/libarch.a /usr/lib/llvm-7/lib/libLLVM-7.so.1 /usr/lib/llvm-7/lib/libclang-7.so.1
/usr/bin/ld: /usr/local/lib/libbfd.a(plugin.o): undefined reference to symbol 'dlsym@@GLIBC_2.17'
/usr/bin/ld: /lib/aarch64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/CMakeFiles/bpftrace.dir/build.make:473: src/bpftrace] Error 1
make[2]: Leaving directory '/data/local/bpftrace/build'
make[1]: *** [CMakeFiles/Makefile2:1205: src/CMakeFiles/bpftrace.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by wingfancy** [comment] 2021-02-28 01:20
Thanks for your help.
I'm building it on adeb(https://github.com/joelagnel/adeb), it's a debin system on Android device.
I built it successfully several days ago. But now I built it again and got failed. Perhaps my system has problem. I'll try to re-install adeb and try again later.

**Comment by wingfancy** [comment] 2021-02-28 04:54
After I re-install the adeb system, the dynamic compile works now. But the static compile not work with the follow failed log. It seems can't find the '-lclang'. But I've installed clang & libclang-dev. Any idea on this issue? Thanks in advance.

```
make[2]: Entering directory '/data/local/home/source/bpftrace/build'
[ 66%] Linking CXX executable bpftrace
cd /data/local/home/source/bpftrace/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/bpftrace.dir/link.txt --verbose=1
/usr/bin/clang++-7  -O3 -DNDEBUG  -static CMakeFiles/bpftrace.dir/attached_probe.cpp.o CMakeFiles/bpftrace.dir/bpffeature.cpp.o CMakeFiles/bpftrace.dir/bpftrace.cpp.o CMakeFiles/bpftrace.dir/btf.cpp.o CMakeFiles/bpftrace.dir/child.cpp.o CMakeFiles/bpftrace.dir/clang_parser.cpp.o CMakeFiles/bpftrace.dir/disasm.cpp.o CMakeFiles/bpftrace.dir/driver.cpp.o CMakeFiles/bpftrace.dir/fake_map.cpp.o CMakeFiles/bpftrace.dir/lockdown.cpp.o CMakeFiles/bpftrace.dir/log.cpp.o CMakeFiles/bpftrace.dir/map.cpp.o CMakeFiles/bpftrace.dir/mapkey.cpp.o CMakeFiles/bpftrace.dir/output.cpp.o CMakeFiles/bpftrace.dir/probe_matcher.cpp.o CMakeFiles/bpftrace.dir/procmon.cpp.o CMakeFiles/bpftrace.dir/printf.cpp.o CMakeFiles/bpftrace.dir/resolve_cgroupid.cpp.o CMakeFiles/bpftrace.dir/signal.cpp.o CMakeFiles/bpftrace.dir/struct.cpp.o CMakeFiles/bpftrace.dir/tracepoint_format_parser.cpp.o CMakeFiles/bpftrace.dir/types.cpp.o CMakeFiles/bpftrace.dir/usdt.cpp.o CMakeFiles/bpftrace.dir/utils.cpp.o CMakeFiles/bpftrace.dir/main.cpp.o  -o bpftrace arch/libarch.a ast/libast.a ../libparser.a ../resources/libresources.a /usr/lib/aarch64-linux-gnu/libbcc.a /usr/lib/aarch64-linux-gnu/libbcc_bpf.a /usr/lib/aarch64-linux-gnu/libbpf.a /usr/lib/aarch64-linux-gnu/libbcc-loader-static.a /usr/lib/aarch64-linux-gnu/libelf.a -lstdc++fs arch/libarch.a -lclang /usr/lib/llvm-7/lib/libclangIndex.a /usr/lib/llvm-7/lib/libclangFormat.a /usr/lib/llvm-7/lib/libclangToolingInclusions.a /usr/lib/llvm-7/lib/libclangFrontend.a /usr/lib/llvm-7/lib/libclangDriver.a /usr/lib/llvm-7/lib/libclangParse.a /usr/lib/llvm-7/lib/libclangSerialization.a /usr/lib/llvm-7/lib/libclangSema.a /usr/lib/llvm-7/lib/libclangAnalysis.a /usr/lib/llvm-7/lib/libclangEdit.a /usr/lib/llvm-7/lib/libclangToolingCore.a /usr/lib/llvm-7/lib/libclangAST.a /usr/lib/llvm-7/lib/libclangRewrite.a /usr/lib/llvm-7/lib/libclangLex.a /usr/lib/llvm-7/lib/libclangBasic.a /usr/lib/llvm-7/lib/libLLVMBPFCodeGen.a /usr/lib/llvm-7/lib/libLLVMMCJIT.a /usr/lib/llvm-7/lib/libLLVMOption.a /usr/lib/llvm-7/lib/libLLVMOrcJIT.a /usr/lib/llvm-7/lib/libLLVMExecutionEngine.a /usr/lib/llvm-7/lib/libLLVMRuntimeDyld.a /usr/lib/llvm-7/lib/libLLVMAArch64CodeGen.a /usr/lib/llvm-7/lib/libLLVMAArch64AsmParser.a /usr/lib/llvm-7/lib/libLLVMAArch64Disassembler.a /usr/lib/llvm-7/lib/libLLVMAArch64Desc.a /usr/lib/llvm-7/lib/libLLVMAArch64AsmPrinter.a /usr/lib/llvm-7/lib/libLLVMAArch64Info.a /usr/lib/llvm-7/lib/libLLVMAArch64Utils.a /usr/lib/llvm-7/lib/libLLVMAMDGPUCodeGen.a /usr/lib/llvm-7/lib/libLLVMAMDGPUAsmParser.a /usr/lib/llvm-7/lib/libLLVMAMDGPUDisassembler.a /usr/lib/llvm-7/lib/libLLVMAMDGPUDesc.a /usr/lib/llvm-7/lib/libLLVMAMDGPUAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMAMDGPUInfo.a /usr/lib/llvm-7/lib/libLLVMAMDGPUUtils.a /usr/lib/llvm-7/lib/libLLVMARMCodeGen.a /usr/lib/llvm-7/lib/libLLVMARMAsmParser.a /usr/lib/llvm-7/lib/libLLVMARMDisassembler.a /usr/lib/llvm-7/lib/libLLVMARMDesc.a /usr/lib/llvm-7/lib/libLLVMARMAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMARMInfo.a /usr/lib/llvm-7/lib/libLLVMARMUtils.a /usr/lib/llvm-7/lib/libLLVMBPFAsmParser.a /usr/lib/llvm-7/lib/libLLVMBPFDesc.a /usr/lib/llvm-7/lib/libLLVMBPFAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMBPFDisassembler.a /usr/lib/llvm-7/lib/libLLVMBPFInfo.a /usr/lib/llvm-7/lib/libLLVMHexagonCodeGen.a /usr/lib/llvm-7/lib/libLLVMHexagonAsmParser.a /usr/lib/llvm-7/lib/libLLVMHexagonDisassembler.a /usr/lib/llvm-7/lib/libLLVMHexagonDesc.a /usr/lib/llvm-7/lib/libLLVMHexagonInfo.a /usr/lib/llvm-7/lib/libLLVMLanaiCodeGen.a /usr/lib/llvm-7/lib/libLLVMLanaiAsmParser.a /usr/lib/llvm-7/lib/libLLVMLanaiDisassembler.a /usr/lib/llvm-7/lib/libLLVMLanaiDesc.a /usr/lib/llvm-7/lib/libLLVMLanaiAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMLanaiInfo.a /usr/lib/llvm-7/lib/libLLVMMipsCodeGen.a /usr/lib/llvm-7/lib/libLLVMMipsAsmParser.a /usr/lib/llvm-7/lib/libLLVMMipsDesc.a /usr/lib/llvm-7/lib/libLLVMMipsAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMMipsDisassembler.a /usr/lib/llvm-7/lib/libLLVMMipsInfo.a /usr/lib/llvm-7/lib/libLLVMMSP430CodeGen.a /usr/lib/llvm-7/lib/libLLVMMSP430Desc.a /usr/lib/llvm-7/lib/libLLVMMSP430AsmPrinter.a /usr/lib/llvm-7/lib/libLLVMMSP430Info.a /usr/lib/llvm-7/lib/libLLVMNVPTXCodeGen.a /usr/lib/llvm-7/lib/libLLVMipo.a /usr/lib/llvm-7/lib/libLLVMIRReader.a /usr/lib/llvm-7/lib/libLLVMAsmParser.a /usr/lib/llvm-7/lib/libLLVMInstrumentation.a /usr/lib/llvm-7/lib/libLLVMLinker.a /usr/lib/llvm-7/lib/libLLVMVectorize.a /usr/lib/llvm-7/lib/libLLVMNVPTXDesc.a /usr/lib/llvm-7/lib/libLLVMNVPTXAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMNVPTXInfo.a /usr/lib/llvm-7/lib/libLLVMPowerPCCodeGen.a /usr/lib/llvm-7/lib/libLLVMPowerPCAsmParser.a /usr/lib/llvm-7/lib/libLLVMPowerPCDesc.a /usr/lib/llvm-7/lib/libLLVMPowerPCAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMPowerPCDisassembler.a /usr/lib/llvm-7/lib/libLLVMPowerPCInfo.a /usr/lib/llvm-7/lib/libLLVMSparcCodeGen.a /usr/lib/llvm-7/lib/libLLVMSparcAsmParser.a /usr/lib/llvm-7/lib/libLLVMSparcDesc.a /usr/lib/llvm-7/lib/libLLVMSparcAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMSparcDisassembler.a /usr/lib/llvm-7/lib/libLLVMSparcInfo.a /usr/lib/llvm-7/lib/libLLVMSystemZCodeGen.a /usr/lib/llvm-7/lib/libLLVMSystemZAsmParser.a /usr/lib/llvm-7/lib/libLLVMSystemZDisassembler.a /usr/lib/llvm-7/lib/libLLVMSystemZDesc.a /usr/lib/llvm-7/lib/libLLVMSystemZAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMSystemZInfo.a /usr/lib/llvm-7/lib/libLLVMX86CodeGen.a /usr/lib/llvm-7/lib/libLLVMGlobalISel.a /usr/lib/llvm-7/lib/libLLVMX86AsmParser.a /usr/lib/llvm-7/lib/libLLVMX86Desc.a /usr/lib/llvm-7/lib/libLLVMX86AsmPrinter.a /usr/lib/llvm-7/lib/libLLVMX86Disassembler.a /usr/lib/llvm-7/lib/libLLVMX86Info.a /usr/lib/llvm-7/lib/libLLVMX86Utils.a /usr/lib/llvm-7/lib/libLLVMXCoreCodeGen.a /usr/lib/llvm-7/lib/libLLVMXCoreDesc.a /usr/lib/llvm-7/lib/libLLVMXCoreAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMXCoreDisassembler.a /usr/lib/llvm-7/lib/libLLVMXCoreInfo.a /usr/lib/llvm-7/lib/libLLVMWebAssemblyCodeGen.a /usr/lib/llvm-7/lib/libLLVMWebAssemblyAsmParser.a /usr/lib/llvm-7/lib/libLLVMWebAssemblyDesc.a /usr/lib/llvm-7/lib/libLLVMWebAssemblyAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMWebAssemblyDisassembler.a /usr/lib/llvm-7/lib/libLLVMWebAssemblyInfo.a /usr/lib/llvm-7/lib/libLLVMAVRCodeGen.a /usr/lib/llvm-7/lib/libLLVMAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMSelectionDAG.a /usr/lib/llvm-7/lib/libLLVMCodeGen.a /usr/lib/llvm-7/lib/libLLVMBitWriter.a /usr/lib/llvm-7/lib/libLLVMScalarOpts.a /usr/lib/llvm-7/lib/libLLVMAggressiveInstCombine.a /usr/lib/llvm-7/lib/libLLVMInstCombine.a /usr/lib/llvm-7/lib/libLLVMTransformUtils.a /usr/lib/llvm-7/lib/libLLVMTarget.a /usr/lib/llvm-7/lib/libLLVMAnalysis.a /usr/lib/llvm-7/lib/libLLVMObject.a /usr/lib/llvm-7/lib/libLLVMBitReader.a /usr/lib/llvm-7/lib/libLLVMProfileData.a /usr/lib/llvm-7/lib/libLLVMCore.a /usr/lib/llvm-7/lib/libLLVMAVRAsmParser.a /usr/lib/llvm-7/lib/libLLVMMCParser.a /usr/lib/llvm-7/lib/libLLVMAVRDesc.a /usr/lib/llvm-7/lib/libLLVMAVRAsmPrinter.a /usr/lib/llvm-7/lib/libLLVMAVRDisassembler.a /usr/lib/llvm-7/lib/libLLVMMCDisassembler.a /usr/lib/llvm-7/lib/libLLVMAVRInfo.a /usr/lib/llvm-7/lib/libLLVMMC.a /usr/lib/llvm-7/lib/libLLVMBinaryFormat.a /usr/lib/llvm-7/lib/libLLVMDebugInfoCodeView.a /usr/lib/llvm-7/lib/libLLVMDebugInfoMSF.a /usr/lib/llvm-7/lib/libLLVMSupport.a -lz -lrt -ldl -ltinfo -lpthread -lm /usr/lib/llvm-7/lib/libLLVMDemangle.a
/usr/bin/ld: cannot find -lclang
/usr/bin/ld: /usr/lib/llvm-7/lib/libLLVMSupport.a(DynamicLibrary.cpp.o): in function `llvm::sys::DynamicLibrary::HandleSet::DLOpen(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
(.text._ZN4llvm3sys14DynamicLibrary9HandleSet6DLOpenEPKcPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x18): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/llvm-7/lib/libLLVMSupport.a(Path.cpp.o): in function `llvm::sys::fs::real_path(llvm::Twine const&, llvm::SmallVectorImpl<char>&, bool)':
(.text._ZN4llvm3sys2fs9real_pathERKNS_5TwineERNS_15SmallVectorImplIcEEb+0x270): warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/llvm-7/lib/libLLVMSupport.a(Path.cpp.o): in function `llvm::sys::path::home_directory(llvm::SmallVectorImpl<char>&)':
(.text._ZN4llvm3sys4path14home_directoryERNS_15SmallVectorImplIcEE+0x9c): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/CMakeFiles/bpftrace.dir/build.make:600: src/bpftrace] Error 1
make[2]: Leaving directory '/data/local/home/source/bpftrace/build'
make[1]: *** [CMakeFiles/Makefile2:1205: src/CMakeFiles/bpftrace.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/data/local/home/source/bpftrace/build'
```

**Comment by fbs** [comment] 2021-02-28 10:59
this looks like a duplicate of your other issue so closing this.

**Closed by fbs** 2021-02-28 10:59 UTC
Labels: bug
