### ISSUE TITLE
`buf()` print `unsigned char *` error

### ISSUE THREAD

**Issue by Rtoax** [iovisor/bpftrace#2215] opened 2022-05-14 10:24 UTC
`buf()` PR https://github.com/iovisor/bpftrace/pull/1107,  @acj 

Does `buf()` support `unsigned char *data` .

```
struct sk_buff {
  unsigned char *data;
  unsigned int data_len;
};
```
when 
```
printf("%r\n", buf($skb->data, $skb->len));
```

get error:

```
bpftrace: /usr/include/llvm/IR/Instructions.h:1207: void llvm::ICmpInst::AssertOK(): Assertion `getOperand(0)->getType() == getOperand(1)->getType() && "Both operands to ICmp instruction are not of the same type!"' failed.
Aborted
```

Does `buf()` support this?

**Comment by viktormalik** [comment] 2022-05-16 07:23
The problem is the `unsigned int` length argument. Should be fixed by the linked PR.

**Closed** 2022-05-16 09:56 UTC
Labels: bug
