### ISSUE TITLE
Error with BEGIN probe containing a map

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#260] opened 2018-11-19 16:31 UTC
If we use a BEGIN probe that contains a map we fail to attach/compile the probe and generate an incorrect error message:
 
```
# bpftrace -e 'BEGIN{@[probe] = count();}'
Wildcard matches aren't available on probe type 'BEGIN'
No probes to attach
```

**Comment by mmarchini** [comment] 2019-01-14 18:03
I'm getting a different error here, but the problem persists:

```bash
./src/bpftrace -e 'BEGIN { @[probe] = 1; }'
objdump: 'a.out': No such file
Attaching 1 probe...
Code not generated for probe: BEGIN
```

**Comment by williangaspar** [comment] 2019-02-25 13:05
The problem is the `probe` builtin

**Comment by mmarchini** [comment] 2019-02-26 16:16
These work:

```
# bpftrace -e 'BEGIN{@ = count();}'
Attaching 1 probe...
^C

@: 1

# bpftrace -e 'BEGIN{@["c"] = count();}'
Attaching 1 probe...
^C

@[c]: 1
```

So the problem is restricted to the `probe` builtin, as @williangaspar suggested. Closing as duplicate of #291.

**Closed by mmarchini** 2019-02-26 16:16 UTC
Labels: bug
