### ISSUE TITLE
why can't trace kretprobe schedule

### ISSUE THREAD

**Issue by tty5** [iovisor/bpftrace#1035] opened 2019-12-26 14:20 UTC
i use here for trace app schedule out and schedule in, but can't trace schedule in.
```
uname -r
5.4.1-1.el7.elrepo.x86_64
------------------------
cat 1.c
int main()
{
    sleep(1);
    return 3;
}
------------------
gcc 1.c
-------------------

./a.out

bpftrace -e 'kprobe:schedule,kretprobe:schedule /comm == "a.out"/{printf("%s\n", probe)}'
Attaching 2 probes...
kprobe:schedule
```

**Comment by tty5** [comment] 2019-12-27 06:45
can use tracepoint:sched:sched_switch for schedule in
and use finish_task_switch for schedule back

**Comment by mmisono** [comment] 2019-12-27 06:53
Is this because of #835? I observed many `nmissed` events.

```
% sudo ./src/bpftrace -e \
'kprobe:unregister_kretprobe {
   $rp = (struct kretprobe*)arg0;
   printf("nmissed=%d, maxactive=%d\n", $rp->nmissed, $rp->maxactive);
}'
Attaching 1 probe...
nmissed=99, maxactive=2
```

**Comment by mmisono** [comment] 2019-12-29 05:52
If I increase `maxactive` manually (the last argument of `bpf_attach_kprobe`), kretprobe fired as expected (and no `nmissed` events).

https://github.com/iovisor/bpftrace/blob/46e62c0fc2b9d52fccc1af9a366cfe8c9552e694/src/attached_probe.cpp#L560-L561

```
% sudo ./src/bpftrace -e 'kprobe:schedule,kretprobe:schedule /comm == "a.out"/{printf("%s\n", probe)}'
Attaching 2 probes...
kprobe:schedule
kretprobe:schedule
```

Perhaps is it nice to introduce `BPFTRACE_MAXACTIVE` environment variable to control `maxactive` value?

**Comment by jordalgo** [comment] 2023-12-20 11:54
Gonna close as duplicate of https://github.com/iovisor/bpftrace/issues/835 - Discussion about adding max active is there.

**Closed by jordalgo** 2023-12-20 11:54 UTC
