### ISSUE TITLE
bpftrace 0.17 crashing on Fedora 37

### ISSUE THREAD

**Issue by caringi** [iovisor/bpftrace#2567] opened 2023-04-17 22:22 UTC
Any plans to release bpftrace 0.18? (This problem doesn't occur in the master branch)

This problem is reproducible on Fedora 37 using bpftrace 0.17:

$ bpftrace -l

```
Program received signal SIGSEGV, Segmentation fault.
btf__type_cnt (btf=0xffffffffffffffea) at btf.c:448
448             return btf->start_id + btf->nr_types;                                                                                          
(gdb) bt
#0  btf__type_cnt (btf=0xffffffffffffffea) at btf.c:448
#1  0x0000555555685a48 in bpftrace::type_cnt (btf=<optimized out>) at /usr/src/debug/bpftrace-0.17.0-1.fc37.x86_64/src/btf.cpp:34
#2  bpftrace::BTF::BTF (this=<optimized out>, modules=..., this=<optimized out>, modules=...)
    at /usr/src/debug/bpftrace-0.17.0-1.fc37.x86_64/src/btf.cpp:62
#3  0x000055555563f17e in bpftrace::BPFfeature::BPFfeature (this=<optimized out>, this=<optimized out>)
    at /usr/src/debug/bpftrace-0.17.0-1.fc37.x86_64/src/bpffeature.h:63
#4  0x0000555555643eba in std::make_unique<bpftrace::BPFfeature> () at /usr/include/c++/12/bits/unique_ptr.h:1065
#5  bpftrace::BPFtrace::BPFtrace (this=<optimized out>, o=..., this=<optimized out>, o=...)
    at /usr/src/debug/bpftrace-0.17.0-1.fc37.x86_64/src/bpftrace.h:97
#6  0x00005555555f5301 in main (argc=<optimized out>, argv=<optimized out>) at /usr/include/c++/12/bits/unique_ptr.h:189
```

### bpftrace --info

```
$ bpftrace --info
System
  OS: Linux 6.2.9-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:31:57 UTC 2023
  Arch: x86_64

Build
  version: v0.17.0
  LLVM: 15.0.7
  unsafe uprobe: no
  bfd: yes
  libdw (DWARF support): no

Segmentation fault (core dumped)
```

backtrace:

```
#0  btf__type_cnt (btf=0xffffffffffffffea) at btf.c:448
#1  0x0000555555685a48 in bpftrace::type_cnt (btf=<optimized out>) at /usr/src/debug/bpftrace-0.17.0-1.fc37.x86_64/src/btf.cpp:34
#2  bpftrace::BTF::BTF (this=<optimized out>, modules=..., this=<optimized out>, modules=...)
    at /usr/src/debug/bpftrace-0.17.0-1.fc37.x86_64/src/btf.cpp:62
#3  0x000055555563f17e in bpftrace::BPFfeature::BPFfeature (this=<optimized out>, this=<optimized out>)
    at /usr/src/debug/bpftrace-0.17.0-1.fc37.x86_64/src/bpffeature.h:63
#4  0x000055555563f930 in info () at /usr/src/debug/bpftrace-0.17.0-1.fc37.x86_64/src/main.cpp:180
#5  parse_args (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/bpftrace-0.17.0-1.fc37.x86_64/src/main.cpp:481
#6  0x00005555555f51ee in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/bpftrace-0.17.0-1.fc37.x86_64/src/main.cpp:681
```

**Comment by viktormalik** [comment] 2023-04-18 06:33
Thanks for reporting this! The problem is related to libbpf 0.8 which Fedora 37 uses (doesn't occur with libbpf 1.0+). The commit that fixes this issue is cd8c1b18.

@fbs what would you suggest? Do we want to do a 0.18 release even if we don't really have much new content? Or do we just backport the fix and release 0.17.1?

**Comment by fbs** [comment] 2023-04-18 06:45
I think it be good to get to a 3m release cycle (or even 2 or 6w) now that development seems to speed up again. Next release on the 1st?

**Comment by viktormalik** [comment] 2023-04-18 06:53
Sounds good. Still, shouldn't we release a fix for this as it makes bpftrace on the latest Fedora practically unusable?

**Comment by fbs** [comment] 2023-04-18 07:42
yeah a 17.1 soumds ok to me if the backport isnt too crazy

**Comment by viktormalik** [comment] 2023-04-18 07:58
The fix applies cleanly on 0.17.0 and basic scripts work, although BTF-based features don't :-( (BTF can't be loaded for some reason)

**Comment by viktormalik** [comment] 2023-04-18 08:39
So I had another look and the root problem is in using libbpf 0.8 which seems to have problems parsing system BTF. While the above commit fixes the segfault, BTF still cannot be parsed and many bpftrace features won't work.

So, the best solution would be if Fedora updated their libbpf version but we can still release 0.17.1 with cd8c1b188df149277c09ebfb208de623a1aeaebb to at least partially mitigate the issue.

**Comment by fbs** [comment] 2023-04-20 20:45
created the release, just need to attach the artifacts when the ci finishes :)

**Comment by viktormalik** [comment] 2023-04-24 05:16
@caringi 0.17.1 is out, do you think that it makes sense to release it in Fedora 37 or should we just wait for the libbpf 1.0 update (not sure how long that will take)? I can help with doing the bpftrace release.

**Comment by caringi** [comment] 2023-04-24 18:50
@viktormalik I was planning to update the bpftrace package for f37 today... 

But looking here:

https://src.fedoraproject.org/rpms/libbpf/commits/f37

Looks like that @olsajiri has already updated the libbpf package for f37 (to 1.1.0).

It's built as well: https://koji.fedoraproject.org/koji/packageinfo?packageID=30017

But what I believe that is missing is the bodhi update entry here:

https://bodhi.fedoraproject.org/updates/?packages=libbpf

What do you think?

**Comment by viktormalik** [comment] 2023-04-24 19:42
I'm not sure if @olsajiri has to wait for the dependent packages to resolve build problems against libbpf 1.0. If he does, it might take some time so I would go with bpftrace update not to have a broken tool there.

**Comment by caringi** [comment] 2023-04-24 22:54
https://bodhi.fedoraproject.org/updates/FEDORA-2023-3b4de9ab16

**Comment by viktormalik** [comment] 2023-04-26 07:04
Thanks! libbpf 1.0 is on the way, too so I think that we can close this.

**Closed by viktormalik** 2023-04-26 07:04 UTC
Labels: bug
