### ISSUE TITLE
Surprising behaviour of static builds

### ISSUE THREAD

**Issue by sezuan** [iovisor/bpftrace#869] opened 2019-08-26 13:01 UTC
I've build a static bpftrace with alpine 3.10/llvm 8. On one host (debian buster with kernel 4.19) this works:

```
bpftrace -B line -e 'tracepoint:syscalls:sys_enter_open { printf("[%s] %s\n", comm, str(args->filename)); }'
```
on another host (stretch, with kernel 4.19) the very same command fails with

```
libclang: crash detected during parsing: {
  'source_filename' : 'definitions.h'
  'command_line_args' : ['clang', '-isystem', '/usr/local/include', '-isystem', '/bpftrace/include', '-isystem', '/usr/include', '-nostdinc', '-isystem', '/virtual/lib/clang/include', '-I/lib/modules/4.19.0-0.bpo.5-amd64/source/arch/x86/include', '-I/lib/modules/4.19.0-0.bpo.5-amd64/build/arch/x86/include/generated', '-I/lib/modules/4.19.0-0.bpo.5-amd64/source/include', '-I/lib/modules/4.19.0-0.bpo.5-amd64/build/include', '-I/lib/modules/4.19.0-0.bpo.5-amd64/source/arch/x86/include/uapi', '-I/lib/modules/4.19.0-0.bpo.5-amd64/build/arch/x86/include/generated/uapi', '-I/lib/modules/4.19.0-0.bpo.5-amd64/source/include/uapi', '-I/lib/modules/4.19.0-0.bpo.5-amd64/build/include/generated/uapi', '-include', '/lib/modules/4.19.0-0.bpo.5-amd64/source/include/linux/kconfig.h', '-D__KERNEL__', '-D__BPF_TRACING__', '-D__HAVE_BUILTIN_BSWAP16__', '-D__HAVE_BUILTIN_BSWAP32__', '-D__HAVE_BUILTIN_BSWAP64__', '-DKBUILD_MODNAME='"bpftrace"'', '-include', 'asm_goto_workaround.h'],
  'unsaved_files' : [('definitions.h', '...', 263), ('/bpftrace/include/__stddef_max_align_t.h', '...', 1771), ('/bpftrace/include/float.h', '...', 5192), ('/bpftrace/include/limits.h', '...', 3735), ('/bpftrace/include/stdarg.h', '...', 2025), ('/bpftrace/include/stddef.h', '...', 4499), ('/bpftrace/include/stdint.h', '...', 23388), ('/bpftrace/include/asm_goto_workaround.h', '...', 667)],
  'options' : 1,
}
```

But with this slight variation:

```
bpftrace -B line -e 'tracepoint:syscalls:sys_enter_open / 0 == 0 / { printf("[%s] %s\n", comm, str(args->filename)); }'
```

it works. I am wondering why this happends.

**Comment by mmarchini** [comment] 2019-10-09 21:16
Maybe related to #266?

**Comment by dalehamel** [comment] 2019-12-22 00:43
Yeah this looks like a dupe of #266, I suggest closing.

RE #266, I commented on #336 a further discovery - it appears that the same thing that makes musl work for a static build may be what is preventing glibc and uclibc from working as a static build, but is also what causes this crash (I think).

**Comment by danobi** [comment] 2019-12-22 02:18
Closing as dupe. Let's track in #266.

**Closed by danobi** 2019-12-22 02:18 UTC
Labels: bug
