### ISSUE TITLE
Call to dladdr() failed with LLVM 10

### ISSUE THREAD

**Issue by florian-kuebler** [iovisor/bpftrace#911] opened 2019-09-26 11:53 UTC
Hi all,
When running `./bpftrace -e 'tracepoint:raw_syscalls:sys_enter { @[comm] = count(); }'` with the newest LLVM and BCC build, bpftrace crashes with the following error.

```
Call to dladdr() failed
UNREACHABLE executed at /llvm-project/clang/tools/libclang/CIndexer.cpp:130!
libclang: crash detected during parsing: {
  'source_filename' : 'definitions.h'
  'command_line_args' : ['clang', '-isystem', '/usr/local/include', '-isystem', '/bpftrace/include', '-isystem', '/usr/include', '-nostdinc', '-isystem', '/virtual/lib/clang/include', '-I/lib/modules/4.19.37-5+deb10u2rodete2-amd64/source/arch/x86/include', '-I/lib/modules/4.19.37-5+deb10u2rodete2-amd64/build/arch/x86/include/generated', '-I/lib/modules/4.19.37-5+deb10u2rodete2-amd64/source/include', '-I/lib/modules/4.19.37-5+deb10u2rodete2-amd64/build/include', '-I/lib/modules/4.19.37-5+deb10u2rodete2-amd64/source/arch/x86/include/uapi', '-I/lib/modules/4.19.37-5+deb10u2rodete2-amd64/build/arch/x86/include/generated/uapi', '-I/lib/modules/4.19.37-5+deb10u2rodete2-amd64/source/include/uapi', '-I/lib/modules/4.19.37-5+deb10u2rodete2-amd64/build/include/generated/uapi', '-include', '/lib/modules/4.19.37-5+deb10u2rodete2-amd64/source/include/linux/kconfig.h', '-D__KERNEL__', '-D__BPF_TRACING__', '-D__HAVE_BUILTIN_BSWAP16__', '-D__HAVE_BUILTIN_BSWAP32__', '-D__HAVE_BUILTIN_BSWAP64__', '-DKBUILD_MODNAME='"bpftrace"'', '-include', 'asm_goto_workaround.h'],
  'unsaved_files' : [('definitions.h', '...', 25), ('/bpftrace/include/__stddef_max_align_t.h', '...', 1771), ('/bpftrace/include/float.h', '...', 5192), ('/bpftrace/include/limits.h', '...', 3735), ('/bpftrace/include/stdarg.h', '...', 2025), ('/bpftrace/include/stddef.h', '...', 4499), ('/bpftrace/include/stdint.h', '...', 23388), ('/bpftrace/include/asm_goto_workaround.h', '...', 667)],
  'options' : 1,
}
```

In order to reproduce this issue, I modified the alpine Dockerfile (which is attached here).
[Dockerfile.alpine.txt](https://github.com/iovisor/bpftrace/files/3657808/Dockerfile.alpine.txt)

**Comment by dalehamel** [comment] 2020-02-24 15:27
this looks like a duplicate of #266 I believe the issue is that libdl functions are stubbed in musl, and that using libdl from a static binary can lead to weird / undefined behavior. 

#917 updates the alpine static build, but I think that a static+libc build with musl would ultimately be the way to fix this for alpine users

**Comment by fbs** [comment] 2020-03-11 00:16
#1190 seems to work is probably an alpine issue.

**Closed by fbs** 2020-03-11 00:16 UTC
Labels: bug, llvm
