### ISSUE TITLE
Get address like "&a"  in C

### ISSUE THREAD

**Issue by Rtoax** [iovisor/bpftrace#2214] opened 2022-05-14 09:27 UTC
Does bpftrace need get vars address like C:

```c
int a;
int *pa = &a;
```

`&` to get address of var, or `addr($task->flags)`

```bpftrace
$task = curtask;
$pflag = &$task->flags;
```

**Comment by fbs** [comment] 2022-05-20 14:04
Just curious, what is the usecase here?

**Comment by viktormalik** [comment] 2023-04-13 11:14
ping @Rtoax, mind sharing a use-case?

**Comment by Rtoax** [comment] 2023-04-21 10:55
Sorry, i forgot what i want in that time, maybe i want to get the offsetof of struct's field.

**Comment by viktormalik** [comment] 2023-09-13 06:13
Duplicate of #553.

**Closed by viktormalik** 2023-09-13 06:13 UTC
Labels: enhancement
