### ISSUE TITLE
Many of the bpftrace subcommands will read the vmlinux file multiple times

### ISSUE THREAD

**Issue by kebe7jun** [iovisor/bpftrace#2408] opened 2022-11-03 07:48 UTC
### What reproduces the bug?

```
# strace -e openat bpftrace -l "*sleep"
openat(AT_FDCWD, "/sys/kernel/btf/vmlinux", O_RDONLY) = 3
openat(AT_FDCWD, "/sys/devices/system/cpu/possible", O_RDONLY) = 3
openat(AT_FDCWD, "/proc/sys/kernel/randomize_va_space", O_RDONLY) = 3
openat(AT_FDCWD, "/sys/kernel/debug/tracing/available_filter_functions", O_RDONLY) = 3
openat(AT_FDCWD, "/dev/null", O_WRONLY) = 5
openat(AT_FDCWD, "/sys/kernel/btf/vmlinux", O_RDONLY) = 5
openat(AT_FDCWD, "/dev/null", O_WRONLY) = 5
openat(AT_FDCWD, "/sys/kernel/btf/vmlinux", O_RDONLY) = 5

```

By looking at the output of strace, it is confirmed that the entire contents of the vmlinux file are read multiple times.
This may be caused by BTF class initialization.

**Comment by viktormalik** [comment] 2022-11-09 07:55
#2315 reworks BTF parsing - `sys/kernel/btf/vmlinux` is no longer used and BTF is parsed using libbpf.

**Comment by viktormalik** [comment] 2023-01-04 13:53
The issue is gone now:
```
# strace -e openat bpftrace -l "*sleep" 2>&1 | grep "/sys/kernel/btf/vmlinux"
#
```
Closing.

**Closed by viktormalik** 2023-01-04 13:53 UTC
Labels: bug
