### ISSUE TITLE
Builtins variable `func` doesn't work in kretprobe

### ISSUE THREAD

**Issue by simpzan** [iovisor/bpftrace#2883] opened 2023-12-15 16:59 UTC
### What reproduces the bug? Provide code if possible.

`test.bt` file is:
```
kprobe:do_sys_openat2,
kprobe:do_sys_open 
{
    printf("%lld %d:%d %s begin\n", nsecs, pid, tid, func);
}

kretprobe:do_sys_openat2,
kretprobe:do_sys_open 
{ 
    printf("%lld %d:%d %s end\n", nsecs, pid, tid, func);
}
```

When I run `bpftrace ./test.bt`, I expect 
```
455181223907207 1:1 do_sys_open begin
455181223927131 1:1 do_sys_openat2 begin
455181223991843 1:1 do_sys_openat2 end
455181223998029 1:1 do_sys_open end
```

But I get
```
455181223907207 1:1 do_sys_open begin
455181223927131 1:1 do_sys_openat2 begin
455181223991843 1:1 __kretprobe_trampoline end
455181223998029 1:1 __kretprobe_trampoline end
```

Is it easy to fix? Or how should I implement it using a thread local stack get the real function name in kretprobe action block? Thanks.

### `bpftrace --info` output
```
System
  OS: Linux 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023
  Arch: x86_64

Build
  version: v0.16.0-91-g3cd8
  LLVM: 12.0.0
  unsafe uprobe: no
  bfd: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  iter:task: yes
  iter:task_file: yes
  kprobe_multi: no
  raw_tp_special: yes

```

**Comment by danobi** [comment] 2023-12-15 17:16
Hi, thanks for the report. This is a known issue and we have a pending fix in https://github.com/iovisor/bpftrace/pull/2645 . Would be good to get that PR merged

**Comment by jordalgo** [comment] 2024-01-06 11:35
Closing as duplicate of https://github.com/iovisor/bpftrace/issues/68

**Closed by jordalgo** 2024-01-06 11:35 UTC
Labels: bug
