### ISSUE TITLE
allow functions (for code reuse)

### ISSUE THREAD

**Issue by aktau** [iovisor/bpftrace#1004] opened 2019-12-09 14:56 UTC
Use case: code re-use, such as when rendering bitfields as text (#958). It would also be easier to encode workarounds like the one mentioned in #999.

I searched open/closed issues and the reference but couldn't find a mention of it. It would look like what one can do in AWK:

```
function print_clone_args(flags) {
        printf(" flags=(");
        printf("%s", $flags & CLONE_CHILD_CLEARTID ? "CLONE_CHILD_CLEARTID|" : "");
        printf("%s", $flags & CLONE_CHILD_SETTID ? "CLONE_CHILD_SETTID|" : "");
        printf("%s", $flags & CLONE_FILES ? "CLONE_FILES|" : "");
        printf("%s", $flags & CLONE_FS ? "CLONE_FS|" : "");
        printf("%s", $flags & CLONE_IO ? "CLONE_IO|" : "");
        printf("%s", $flags & CLONE_NEWCGROUP ? "CLONE_NEWCGROUP|" : "");
        printf("%s", $flags & CLONE_NEWIPC ? "CLONE_NEWIPC|" : "");
        printf("%s", $flags & CLONE_NEWNET ? "CLONE_NEWNET|" : "");
        printf("%s", $flags & CLONE_NEWNS ? "CLONE_NEWNS|" : "");
        printf("%s", $flags & CLONE_NEWPID ? "CLONE_NEWPID|" : "");
        printf("%s", $flags & CLONE_NEWUSER ? "CLONE_NEWUSER|" : "");
        printf("%s", $flags & CLONE_NEWUTS ? "CLONE_NEWUTS|" : "");
        printf("%s", $flags & CLONE_PARENT ? "CLONE_PARENT|" : "");
        printf("%s", $flags & CLONE_PARENT_SETTID ? "CLONE_PARENT_SETTID|" : "");
        printf("%s", $flags & CLONE_PTRACE ? "CLONE_PTRACE|" : "");
        printf("%s", $flags & CLONE_SETTLS ? "CLONE_SETTLS|" : "");
        printf("%s", $flags & CLONE_SIGHAND ? "CLONE_SIGHAND|" : "");
        printf("%s", $flags & CLONE_SYSVSEM ? "CLONE_SYSVSEM|" : "");
        printf("%s", $flags & CLONE_THREAD ? "CLONE_THREAD|" : "");
        printf("%s", $flags & CLONE_UNTRACED ? "CLONE_UNTRACED|" : "");
        printf("%s", $flags & CLONE_VFORK ? "CLONE_VFORK|" : "");
        printf("%s", $flags & CLONE_VM ? "CLONE_VM|" : "");
        printf(")");
}

tracepoint:syscalls:sys_enter_clone {
  print_clone_args(args->clone_flags);
}
```

This example only has a single invocation of `print_clone_args`, but in my specific use-case I want to display the clone flags on the `sys_exit_clone` event sometimes (based on a command-line flag). It would be useful not to duplicate that code.

It would probably be preferable if it these functions could have return values:

```
function clone_args(flags) {
        $ret += $flags & CLONE_CHILD_CLEARTID ? "CLONE_CHILD_CLEARTID|" : "";
        // ...
        return $ret;
}
```

Currently this wouldn't work for strings since AFAIK you cannot save new strings in a variable, but maybe in the future.

Since this seems like an obvious FR, I may have missed an earlier discussion on this. I did search for open and closed issues (for "function" and "abstraction"). In that case, please feel free to close this and point to me where this was discussed. Thanks!

**Comment by aleclearmind** [comment] 2020-03-28 22:37
[My current approach](https://github.com/aleclearmind/gource-fun/blob/master/trace-fds.bt) is to preprocess the `.bt` file using the C preprocessor so I can use `#define`. It's rather brutal, but it works.
If deemed reasonable, it might make sense to run `cpp` on the input programs by default.

**Comment by lenticularis39** [comment] 2023-03-07 08:39
Opened #2516 with an RFC for this feature.

**Comment by jordalgo** [comment] 2023-12-20 11:44
Closing as duplicate of https://github.com/iovisor/bpftrace/issues/2516 (we'll track discussion there)

**Closed by jordalgo** 2023-12-20 11:44 UTC
Labels: enhancement
