### ISSUE TITLE
Fix codegen tests

### ISSUE THREAD

**Issue by ajor** [iovisor/bpftrace#187] opened 2018-10-16 19:38 UTC

**Comment by dalehamel** [comment] 2018-11-27 21:38
The current approach is basically just fixture comparison, and as I understand it we only see differences because different versions of LLVM may generate different IR.

What if we only ran the codegen tests against a "bespoke" image, so that we could hold the LLVM version constant, and have other pipelines filter out codegen tests. This would also be helpful when generating new tests, as this "bespoke" image would allow for a reproducible setup for producing the test fixture.

**Comment by mmarchini** [comment] 2019-01-14 18:07
Codegen tests are fixed on `master`, so I'll close this issue for now. Feel free to reopen if there's anything left to be done.

**Closed by mmarchini** 2019-01-14 18:07 UTC
