### ISSUE TITLE
Printing pointer stored in a global map fails in the verifier

### ISSUE THREAD

**Issue by javierhonduco** [iovisor/bpftrace#931] opened 2019-10-30 15:05 UTC
Trying to debug #930 I stumbled upon code generation that produces code that is rejected by the verifier, only when the variable is global:

## Seems to work
```C
#include <linux/mm.h>

kprobe:do_wp_page
{
    $a = (struct vm_fault*)arg0;
    printf("%llx\n", $a);
    exit();
}
```
```
Attaching 1 probe...
ffffc90007093e28
```

## Does not seem to work
```C
#include <linux/mm.h>

kprobe:do_wp_page
{
    @a = (struct vm_fault*)arg0;
    printf("%llx\n", @a);
    exit();
}
```
```
Attaching 1 probe...
Error loading program: kprobe:do_wp_page (try -v)
```

<details>
  <summary>Verifier output running `bpftrace -v`:</summary>
  
```
Error log:
0: (bf) r6 = r1
1: (79) r3 = *(u64 *)(r6 +112)
2: (b7) r8 = 0
3: (7b) *(u64 *)(r10 -8) = r8
4: (bf) r7 = r10
5: (07) r7 += -32
6: (bf) r1 = r7
7: (b7) r2 = 8
8: (85) call bpf_probe_read#4
9: (18) r1 = 0xffff880018a38c00
11: (bf) r2 = r10
12: (07) r2 += -8
13: (bf) r3 = r7
14: (b7) r4 = 0
15: (85) call bpf_map_update_elem#2
16: (7b) *(u64 *)(r10 -24) = r8
17: (7b) *(u64 *)(r10 -32) = r8
18: (7b) *(u64 *)(r10 -16) = r8
19: (18) r1 = 0xffff880018a38c00
21: (bf) r2 = r10
22: (07) r2 += -16
23: (85) call bpf_map_lookup_elem#1
24: (15) if r0 == 0x0 goto pc+22
 R0=map_value(id=0,off=0,ks=8,vs=8,imm=0) R6=ctx(id=0,off=0,imm=0) R7=fp-32,call_-1 R8=inv0 R10=fp0,call_-1 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=00000000 fp-32=00000000
25: (71) r2 = *(u8 *)(r0 +1)
 R0=map_value(id=0,off=0,ks=8,vs=8,imm=0) R6=ctx(id=0,off=0,imm=0) R7=fp-32,call_-1 R8=inv0 R10=fp0,call_-1 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=00000000 fp-32=00000000
26: (67) r2 <<= 8
27: (71) r1 = *(u8 *)(r0 +0)
 R0=map_value(id=0,off=0,ks=8,vs=8,imm=0) R2_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R6=ctx(id=0,off=0,imm=0) R7=fp-32,call_-1 R8=inv0 R10=fp0,call_-1 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=00000000 fp-32=00000000
28: (4f) r2 |= r1
29: (71) r1 = *(u8 *)(r0 +3)
 R0=map_value(id=0,off=0,ks=8,vs=8,imm=0) R1_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R2_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=fp-32,call_-1 R8=inv0 R10=fp0,call_-1 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=00000000 fp-32=00000000
30: (67) r1 <<= 8
31: (71) r3 = *(u8 *)(r0 +2)
 R0=map_value(id=0,off=0,ks=8,vs=8,imm=0) R1_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R2_w=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=fp-32,call_-1 R8=inv0 R10=fp0,call_-1 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=00000000 fp-32=00000000
32: (4f) r1 |= r3
33: (67) r1 <<= 16
34: (4f) r1 |= r2
35: (71) r2 = *(u8 *)(r0 +5)
 R0=map_value(id=0,off=0,ks=8,vs=8,imm=0) R1_w=inv(id=0) R2_w=inv(id=0) R3_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=fp-32,call_-1 R8=inv0 R10=fp0,call_-1 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=00000000 fp-32=00000000
36: (67) r2 <<= 8
37: (71) r3 = *(u8 *)(r0 +4)
 R0=map_value(id=0,off=0,ks=8,vs=8,imm=0) R1_w=inv(id=0) R2_w=inv(id=0,umax_value=65280,var_off=(0x0; 0xff00)) R3_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=fp-32,call_-1 R8=inv0 R10=fp0,call_-1 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=00000000 fp-32=00000000
38: (4f) r2 |= r3
39: (71) r3 = *(u8 *)(r0 +6)
 R0=map_value(id=0,off=0,ks=8,vs=8,imm=0) R1_w=inv(id=0) R2_w=inv(id=0) R3_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=fp-32,call_-1 R8=inv0 R10=fp0,call_-1 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=00000000 fp-32=00000000
40: (71) r8 = *(u8 *)(r0 +7)
 R0=map_value(id=0,off=0,ks=8,vs=8,imm=0) R1_w=inv(id=0) R2_w=inv(id=0) R3_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=fp-32,call_-1 R8_w=inv0 R10=fp0,call_-1 fp-8=mmmmmmmm fp-16=mmmmmmmm fp-24=00000000 fp-32=00000000
41: (67) r8 <<= 8
42: (4f) r8 |= r3
43: (67) r8 <<= 16
44: (4f) r8 |= r2
45: (67) r8 <<= 32
46: (4f) r8 |= r1
47: (7b) *(u64 *)(r10 -8) = r8
48: (bf) r1 = r10
49: (07) r1 += -8
50: (7b) *(u64 *)(r10 -24) = r1
51: (18) r7 = 0xffff880133671e00
53: (85) call bpf_get_smp_processor_id#8
54: (bf) r4 = r10
55: (07) r4 += -32
56: (bf) r1 = r6
57: (bf) r2 = r7
58: (bf) r3 = r0
59: (b7) r5 = 16
60: (85) call bpf_perf_event_output#25
invalid indirect read from stack off -32+8 size 16
processed 58 insns (limit 1000000) max_states_per_insn 0 total_states 5 peak_states 5 mark_read 5

Error loading program: kprobe:do_wp_page
```
</details>

cc @tyroguru 

I'm running `bpftrace v0.9.2` and `Linux 4.16.18`

Thanks,

**Comment by fbs** [comment] 2019-11-12 10:04
Looks like the same issue as in #930 which was fixed by #949. Can't reproduce on master

**Closed by fbs** 2019-11-12 10:04 UTC
