### ISSUE TITLE
Choosing of an associative array depending on the condition

### ISSUE THREAD

**Issue by ech0-py** [iovisor/bpftrace#738] opened 2019-06-08 08:52 UTC
```
@b[1] = "b1"
@b[2] = "b2"
@b[3] = "b3"

@c[1] = "c4"
@c[2] = "c5"
@c[3] = "c6"

@var = "c"
if (@var == "b"){
  @ret_arr = @b
}
if (@var == "c"){
  @ret_arr = @c
}
printf("%s", @ret_arr[1])
```
Is this possible at the moment? printf returns an empty value

**Comment by jordalgo** [comment] 2023-12-14 19:50
Closing as duplicate of: https://github.com/iovisor/bpftrace/issues/686

**Closed by jordalgo** 2023-12-14 19:50 UTC
Labels: question
