### ISSUE TITLE
ustack is not readable 

### ISSUE THREAD

**Issue by bitzhuxb** [iovisor/bpftrace#2503] opened 2023-02-08 03:26 UTC
### What reproduces the bug?
hello,  I have a question of bpftrace:
```
 bpftrace -e 'uprobe:./log-server:io.copyBuffer /comm == "log-server"/ { printf("%s %d %s %s\n", comm, pid,ustack,kstack); }' 2>&1
Attaching 1 probe...
log-server 55235
        0x4b5f00
        0x6f8d05
        0x6e274d
        0x9b1139
        0xb19279
        0xb12345
        0xb13706
        0xb37079
        0xb366ce
        0xb363fd 
```       
the above stack is not readable ，how to change the command so that the stack is readable. 

### bpftrace --info
```
System
  OS: Linux 4.18.0-147.mt20200626.413.el8_1.x86_64 #1 SMP Fri Jun 26 10:27:19 CST 2020
  Arch: x86_64

Build
  version: v0.13.0
  LLVM: 12.0.0
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: yes
  send_signal: no
  override_return: no
  get_boot_ns: no
  dpath: no

Kernel features
  Instruction limit: 131072
  Loop support: no
  btf (depends on Build:libbpf): no
  map batch (depends on Build:libbpf): no
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
  iter:task: no
  iter:task_file: no
```

**Comment by fbs** [comment] 2023-02-08 19:45
Do you have debug symbols voor log-server?

**Comment by bitzhuxb** [comment] 2023-02-12 12:36
> Do you have debug symbols voor log-server?

Yes， by using bpftrace -l 'uprobe:log-server:*' ,  many symbols are listed in the screen

**Comment by viktormalik** [comment] 2023-02-14 06:00
The output seems a bit strange. You're printing `ustack` and `kstack` but what we see on the top seems like only the `ustack`. Did you crop the output?

**Comment by lenticularis39** [comment] 2023-02-15 12:44
This looks like a duplicate of #2284. Consider two programs, gotest.go:
```go
package main

import (
    "fmt"
    "io"
    "os"
    "strings"
)

func main() {
    src := strings.NewReader("GfG\n")
    dst := os.Stdout
    buffer := make([]byte, 1)
    bytes, err := io.CopyBuffer(dst, src, buffer)
    if err != nil {
        panic(err)
    }
    fmt.Printf("The number of bytes are: %d\n", bytes)
}
```
and gotest-sleep.go:
```go
package main

import (
    "fmt"
    "io"
    "os"
    "strings"
    "time"
)

func main() {
    src := strings.NewReader("GfG\n")
    dst := os.Stdout
    buffer := make([]byte, 1)
    bytes, err := io.CopyBuffer(dst, src, buffer)
    if err != nil {
        panic(err)
    }
    fmt.Printf("The number of bytes are: %d\n", bytes)
    time.Sleep(1 * time.Second)
}
```
With these, I get:
```
# bpftrace -e 'uprobe:/tmp/gotest/gotest:io.copyBuffer { print(func);  }'
Attaching 1 probe...
0x473980
# bpftrace -e 'uprobe:/tmp/gotest/gotest-sleep:io.copyBuffer { print(func);  }'
Attaching 1 probe...
io.copyBuffer
```

Merging #2386 should fix your issue if either ASLR is disabled or `log-server` is running at the time of attaching the probe and `BPFTRACE_CACHE_USER_SYMBOLS` environmental variable is set to `PER_PID`.

**Comment by viktormalik** [comment] 2023-04-04 09:06
ping @bitzhuxb, could you give it a try with #2386?

**Comment by jordalgo** [comment] 2024-01-04 23:19
Closing due to inactivity. Feel free to re-open if this is still a problem.

**Closed by jordalgo** 2024-01-04 23:19 UTC
Labels: bug, waiting-on-author
