### ISSUE TITLE
Can't read mm_struct fields

### ISSUE THREAD

**Issue by jeromemarchand** [iovisor/bpftrace#901] opened 2019-09-20 13:39 UTC
I'm trying to read mm_struct fields and got some strange result: all field seem to have the same value.

```
#!/usr/bin/bpftrace

#include <linux/sched.h>

kprobe:do_sys_open
{
	$task = (struct task_struct *)curtask;
	$mm = (struct mm_struct *) $task->mm;
	printf("Some random fields: %lx %lx %lx\n",
		$mm->mmap, $mm->start_code, $mm->hmm);
}
```

```
$ bpftrace --version
bpftrace v0.9.2
$ sudo ./test.bt
Attaching 1 probe...
Some random fields: ffff8e6465cdfaf0 ffff8e6465cdfaf0 ffff8e6465cdfaf0
Some random fields: ffff8e6474a10000 ffff8e6474a10000 ffff8e6474a10000
Some random fields: ffff8e6473371c80 ffff8e6473371c80 ffff8e6473371c80
Some random fields: ffff8e646f7d3320 ffff8e646f7d3320 ffff8e646f7d3320
Some random fields: ffff8e6474a10000 ffff8e6474a10000 ffff8e6474a10000
```

All field in mm_struct are contained in an anonymous struct, except the last one which is a flexible array. That's probably related to the issue.

There is no problem when accessing mm_struct with bcc version 0.10.0.

```
#!/usr/bin/python3

from bcc import BPF

bpf_text = """
#include <linux/sched.h>

int trace_sys_open(struct pt_regs *ctx, long code) {
    struct task_struct *t = (struct task_struct *)bpf_get_current_task();
    struct mm_struct *mm = t->mm;

    bpf_trace_printk("Some random fields: %lx %lx %lx\\n",
		     mm->mmap, mm->start_code, mm->hmm);

    return 0;
}
"""

b = BPF(text=bpf_text)
b.attach_kprobe(event="do_sys_open", fn_name="trace_sys_open")

while 1:
    try:
        (task, pid, cpu, flags, ts, msg) = b.trace_fields()
    except ValueError:
        continue
    print("%-12s %-6d %s" % (task, pid, msg))
```

```
$ sudo ./test.py
b'python3'   2020   b'Some random fields: ffff8e61c1fb8ed8 556ce6743000 0'
b'python3'   2020   b'Some random fields: ffff8e61c1fb8ed8 556ce6743000 0'
b'python3'   2020   b'Some random fields: ffff8e61c1fb8ed8 556ce6743000 0'
b'<...>'     2909   b'Some random fields: ffff8e63912d44b0 55720184e000 0'
b'libvirtd'  1685   b'Some random fields: ffff8e6486fa0960 555c01c97000 0'
b'libvirtd'  1685   b'Some random fields: ffff8e6486fa0960 555c01c97000 0'
```

**Comment by fbs** [comment] 2019-09-20 15:32
Which bpftrace and kernel is this? 

I cannot reproduce it my vagrant ubuntu-18.10 machine with bpftrace master:

```
Some random fields: apparmor_parser 15509 ffff8e0c760d3340 557127f0b000 0
Some random fields: command-not-fou 15496 ffff8e0cb76c3680 400000 0
Some random fields: command-not-fou 15497 ffff8e0cb783b410 400000 0
Some random fields: ls 15494 ffff8e0cb83514e0 5564fdd9c000 0
````

Can you add the generated bpf code. This can be done by running with `-v` or using `sudo bpftool prog dump xlated id <...>`

**Comment by jeromemarchand** [comment] 2019-09-23 09:29
This is on Fedora 30, kernel version is 5.2.9-200.fc30.x86_64 and bpftrace is v0.9.2

```
Bytecode: 
0: (bf) r6 = r1
1: (85) call bpf_get_current_task#35
2: (07) r0 += 1144
3: (bf) r1 = r10
4: (07) r1 += -40
5: (b7) r2 = 8
6: (bf) r3 = r0
7: (85) call bpf_probe_read#4
8: (79) r7 = *(u64 *)(r10 -40)
9: (b7) r1 = 0
10: (7b) *(u64 *)(r10 -40) = r1
11: (bf) r1 = r10
12: (07) r1 += -8
13: (b7) r2 = 8
14: (bf) r3 = r7
15: (85) call bpf_probe_read#4
16: (79) r1 = *(u64 *)(r10 -8)
17: (7b) *(u64 *)(r10 -32) = r1
18: (bf) r1 = r10
19: (07) r1 += -8
20: (b7) r2 = 8
21: (bf) r3 = r7
22: (85) call bpf_probe_read#4
23: (79) r1 = *(u64 *)(r10 -8)
24: (7b) *(u64 *)(r10 -24) = r1
25: (bf) r1 = r10
26: (07) r1 += -8
27: (b7) r2 = 8
28: (bf) r3 = r7
29: (85) call bpf_probe_read#4
30: (79) r1 = *(u64 *)(r10 -8)
31: (7b) *(u64 *)(r10 -16) = r1
32: (18) r7 = 0xffff8e63755b6400
34: (85) call bpf_get_smp_processor_id#8
35: (bf) r4 = r10
36: (07) r4 += -40
37: (bf) r1 = r6
38: (bf) r2 = r7
39: (bf) r3 = r0
40: (b7) r5 = 32
41: (85) call bpf_perf_event_output#25
42: (b7) r0 = 0
43: (95) exit
processed 43 insns (limit 1000000) max_states_per_insn 0 total_states 7 peak_states 7 mark_read 6
```

**Comment by jeromemarchand** [comment] 2019-09-23 09:41
Ubuntu 18.10 have a 4.18 kernel. The mm_struct in that version doesn't have the anonymous nor the flexible array that may baffle bpftrace.

v4.18:
```
struct mm_struct {
	struct vm_area_struct *mmap;		/* list of VMAs */
	struct rb_root mm_rb;
[...]
#if IS_ENABLED(CONFIG_HMM)
	/* HMM needs to track a few things per mm */
	struct hmm *hmm;
#endif
} __randomize_layout;
```
v5.2:
```
struct mm_struct {
	struct {
		struct vm_area_struct *mmap;		/* list of VMAs */
		struct rb_root mm_rb;
[...]
#if IS_ENABLED(CONFIG_HMM)
		/* HMM needs to track a few things per mm */
		struct hmm *hmm;
#endif
	} __randomize_layout;

	/*
	 * The mm_cpumask needs to be at the end of mm_struct, because it
	 * is dynamically sized based on nr_cpu_ids.
	 */
	unsigned long cpu_bitmap[];
};
```

**Comment by jeromemarchand** [comment] 2019-09-25 14:24
I have done a bit of testing.

test_struct.h:
```
struct foo {
	struct {
		int a;
		int b;
		int c;
	} __randomize_layout;
	int flex[];
};
```

test_struct.c:
```
#define __randomize_layout __attribute__((randomize_layout))
#include "test_struct.h"

int func(struct foo *f) {
	return f->a;	
}

int main() {
	struct foo f;
	f.a = 111;
	f.b = 222;
	f.c = 333;
	func(&f);

	return 0;
}
```

test_struct.bt:
```
#!/usr/bin/bpftrace

#define __randomize_layout
#include "test_struct.h"

uprobe:./test_struct:func
{
	$f = (struct foo *)arg0;
	printf("a: %d - b: %d - c: %d\n", $f->a, $f->b, $f->c);
```

Notice how __randomize_layout is defined differently depending on the compiler in the kernel. That's what I reproduced here.

```
$ sudo bpftrace -v ./test_struct.bt 
Attaching 1 probe...

Program ID: 75

Bytecode: 
0: (bf) r6 = r1
1: (79) r7 = *(u64 *)(r6 +112)
2: (b7) r1 = 0
3: (7b) *(u64 *)(r10 -16) = r1
4: (7b) *(u64 *)(r10 -24) = r1
5: (7b) *(u64 *)(r10 -32) = r1
6: (7b) *(u64 *)(r10 -40) = r1
7: (bf) r1 = r10
8: (07) r1 += -4
9: (b7) r2 = 4
10: (bf) r3 = r7
11: (85) call bpf_probe_read#4
12: (61) r1 = *(u32 *)(r10 -4)
13: (63) *(u32 *)(r10 -32) = r1
14: (bf) r1 = r10
15: (07) r1 += -4
16: (b7) r2 = 4
17: (bf) r3 = r7
18: (85) call bpf_probe_read#4
19: (61) r1 = *(u32 *)(r10 -4)
20: (63) *(u32 *)(r10 -24) = r1
21: (bf) r1 = r10
22: (07) r1 += -4
23: (b7) r2 = 4
24: (bf) r3 = r7
25: (85) call bpf_probe_read#4
26: (61) r1 = *(u32 *)(r10 -4)
27: (63) *(u32 *)(r10 -16) = r1
28: (18) r7 = 0xffff97c30a939200
30: (85) call bpf_get_smp_processor_id#8
31: (bf) r4 = r10
32: (07) r4 += -40
33: (bf) r1 = r6
34: (bf) r2 = r7
35: (bf) r3 = r0
36: (b7) r5 = 32
37: (85) call bpf_perf_event_output#25
38: (b7) r0 = 0
39: (95) exit
processed 39 insns (limit 1000000) max_states_per_insn 0 total_states 5 peak_states 5 mark_read 4

Attaching uprobe:./test_struct:func
Running...
a: 111 - b: 111 - c: 111
```

If I remove the flexible array, or replace it by a simple integer, bpftrace works correctly:
```
$ sudo ./test_struct.bt 
Attaching 1 probe...
a: 111 - b: 222 - c: 333
```

**Comment by jeromemarchand** [comment] 2019-09-25 14:30
LLVM version is 8.0.0. I suspect the issue is related with the special handling of LLVM 8 in is_anonymous():
```
  // In LLVM 8, some structs which the above function says are anonymous
  // are actually not. We iterate through the siblings of our struct
  // definition to see if there is a field giving it a name.
  //
  // struct Parent                 struct Parent
  // {                             {
  //   struct                        struct
  //   {                             {
  //     ...                           ...
  //   } name;                       };
  //   int sibling;                  int sibling;
  // };                            };
  //
  // Children of parent:           Children of parent:
  //   Struct: (cursor c)            Struct: (cursor c)
  //   Field:  (Record)name          Field:  (int)sibling
  //   Field:  (int)sibling
  //
  // Record field found after      No record field found after
  // cursor - not anonymous        cursor - anonymous
```

**Comment by viktormalik** [comment] 2023-08-04 14:25
This looks like a problem specific to LLVM 8.0 which is not supported by bpftrace anymore.

Closing.

**Closed by viktormalik** 2023-08-04 14:25 UTC
Labels: bug
