### ISSUE TITLE
2-arg str() call in USDT fails

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#1672] opened 2021-01-12 01:54 UTC
Copied from: https://github.com/iovisor/bpftrace/pull/1671:

---

This is rather a bug report with failing tests instead of a patch to fix problems.

## Environment

* Ubuntu 20.04.1 / Kernel 5.4.0-58-generic
* bpftrace 0f7cd742cb2f71426e07d21f27d550e6a12c2387 (latest as of Jan 8 2021)

## Problems

`str(arg0, arg1)` does not work in USDT, where arg0 is `const char*` and arg1 is `size_t` in the target C program.

To be exact, given `const char* s = "..."` and `size_t s_len = strlen(s)` in the C program, emitting an event with `DTRACE_PROBE2(test, probe1, s, s_len)`, and the bpftrace script is something like this:

```
usdt:./testprogs/usdt_call_str_2:test:probe1 {
  printf("<%s>\n", str(arg0, arg1));
  exit();
}
```

It results in `<>`, where it is expected to be `<hello>` (`NAME "usdt call 2-arg str()"
`).  If the second arg is converted to `int` in the C program, it passes (`NAME "usdt call 2-arg str() with int"
`).

Also, `printf("<%s>\n", str(arg0, (int32)arg1));` fails with assertion failure, as the test script includes (`NAME "usdt call 2-arg str() with cast"
`).

## How to reproduce this problem

See the diff in the PR.

**Comment by mmisono** [comment] 2021-01-15 10:30
It seems this is also due to #1305.

```
% sudo ./src/bpftrace -e 'U:./a:test:probe1 { printf("%s\n", str(arg0, arg1));  }'

% sudo ./bpftool prog dump xlated id 410
   0: (bf) r6 = r1
   1: (b7) r8 = 0
   2: (7b) *(u64 *)(r10 -144) = r8
   3: (7b) *(u64 *)(r10 -136) = r8
   4: (7b) *(u64 *)(r10 -128) = r8
   5: (7b) *(u64 *)(r10 -120) = r8
   6: (7b) *(u64 *)(r10 -112) = r8
   7: (7b) *(u64 *)(r10 -104) = r8
   8: (7b) *(u64 *)(r10 -96) = r8
   9: (7b) *(u64 *)(r10 -88) = r8
  10: (7b) *(u64 *)(r10 -80) = r8
  11: (79) r3 = *(u64 *)(r6 +32)
  12: (7b) *(u64 *)(r10 -72) = r8
  13: (07) r3 += -8
  14: (bf) r1 = r10
  15: (07) r1 += -72
  16: (b7) r2 = 8
  17: (85) call bpf_probe_read_user#-60112
  18: (7b) *(u64 *)(r10 -72) = r8 // <-------- bpf_probe_read_user() results is overwritten
[...]
```

**Comment by michaelgugino** [comment] 2021-10-04 17:09
I'm on LLVM 11.0 and noticed this same behavior (tracing golang).  Another bug mentioned passing `-kk` to fix, and indeed it worked.  However, I am still reproducing the issue with `-kk` if I try to substitute a variable for an sarg:

```
[~]# bpftrace -e 'uprobe:/proc/892262/exe:"main.f1" { $mysarg2 = sarg2; printf("mysarg2 %d str(sarg1, sarg2): %s\n", $mysarg2, str(sarg1, $mysarg2)); }' -kk
Attaching 1 probe...
mysarg2 0 str(sarg1, sarg2): 
mysarg2 0 str(sarg1, sarg2): 
^C

[~]# bpftrace -e 'uprobe:/proc/892262/exe:"main.f1" { $mysarg2 = sarg2; printf("mysarg2 %d str(sarg1, sarg2): %s\n", $mysarg2, str(sarg1, sarg2)); }' -kk
Attaching 1 probe...
mysarg2 5 str(sarg1, sarg2): hi go
mysarg2 5 str(sarg1, sarg2): hi go
```

What's really wild is if I increment $mysarg2, the value of 6 persists:
```
# bpftrace -e 'uprobe:/proc/892262/exe:"main.f1" { $mysarg2 = sarg2+1; printf("mysarg2 %d str(sarg1, sarg2): %s\n", $mysarg2, str(sarg1, $mysarg2)); }'
Attaching 1 probe...
mysarg2 6 str(sarg1, sarg2): hi goi
mysarg2 6 str(sarg1, sarg2): hi goi
```

The last char is garbage data.

If I use an increment, copy, decrement, `-kk` gives incorrect behavior and without correct:

```
# bpftrace -e 'uprobe:/proc/892262/exe:"main.f1" { $mysarg2 = sarg2+1; $mytemp = $mysarg2-1; printf("mysarg2 %d str(sarg1, sarg2): %s\n", $mysarg2, str(sarg1, $mytemp)); }'
Attaching 1 probe...
mysarg2 6 str(sarg1, sarg2): hi go
mysarg2 6 str(sarg1, sarg2): hi go
^C

# bpftrace -e 'uprobe:/proc/892262/exe:"main.f1" { $mysarg2 = sarg2+1; $mytemp = $mysarg2-1; printf("mysarg2 %d str(sarg1, sarg2): %s\n", $mysarg2, str(sarg1, $mytemp)); }' -kk
Attaching 1 probe...
mysarg2 1 str(sarg1, sarg2): 
mysarg2 1 str(sarg1, sarg2): 
```
It seems variable assignment is doesn't actually occur in all cases.

**Comment by viktormalik** [comment] 2023-01-06 10:11
This is working on the latest bpftrace with LLVM 14 so the problem indeed seems to be related to #1305.

Closing.

**Closed by viktormalik** 2023-01-06 10:11 UTC
Labels: bug
