### ISSUE TITLE
Permission error when building docker images with libbpf

### ISSUE THREAD

**Issue by caizixian** [iovisor/bpftrace#2317] opened 2022-08-04 12:02 UTC
### What reproduces the bug?
As suggested in #2303, libbpf needs to be built from source before building bpftrace.

I added `-e BUILD_LIBBPF=ON` to https://github.com/iovisor/bpftrace/blob/05cfa8e6cde2d16cdaabe4ad16eb7fd4d793b6ec/build-static.sh#L7

However, libbpf will fail to build, because it doesn't have permission to write to `/src`.

Deleting `-u $(id -u):$(id -g)` on the same line would work but the user will need to run `chmod -R` on the host to fix the permission.

### Potential fix
Build libbpf when building `bpftrace-builder`, such as in https://github.com/iovisor/bpftrace/blob/05cfa8e6cde2d16cdaabe4ad16eb7fd4d793b6ec/docker/Dockerfile.ubuntu-glibc#L59

**Comment by viktormalik** [comment] 2022-08-08 08:40
libbpf is built as a part of bcc inside `docker/Dockerfile.ubuntu-glibc` but the problem is that libbpf headers were not installed there. This should be fixed by #2319, could you give it a try? Thanks!

**Closed** 2022-08-08 09:09 UTC
Labels: bug

**Comment by caizixian** [comment] 2022-08-10 01:05
Thanks @viktormalik . I can confirm that `./build-static.sh` works for me now.
