### ISSUE TITLE
different libc.so.6 path in CentOS 7 distro

### ISSUE THREAD

**Issue by yujinqiu** [iovisor/bpftrace#219] opened 2018-10-26 12:21 UTC
Hi, 
In CentOS 7 distro the libc.so.6  is  /lib64/libc.so.6  not  /lib/x86_64-linux-gnu/libc.so.6. 
I wonder how can we make it compatible between different Linux distro ?

```

./bpftrace gethostlatency.bt
Attaching 7 probes...
Could not resolve symbol: /lib/x86_64-linux-gnu/libc.so.6:gethostbyname2

```
change to `/lib64/libc.so.6:getaddrinfo` it work as expect. 
```
BEGIN
{
	printf("Tracing getaddr/gethost calls... Hit Ctrl-C to end.\n");
	printf("%-9s %-6s %-16s %6s %s\n", "TIME", "PID", "COMM", "LATms",
	    "HOST");
}

uprobe:/lib64/libc.so.6:getaddrinfo,
uprobe:/lib64/libc.so.6:gethostbyname,
uprobe:/lib64/libc.so.6:gethostbyname2
{
	@start[tid] = nsecs;
	@name[tid] = arg0;
}

uretprobe:/lib64/libc.so.6:getaddrinfo,
uretprobe:/lib64/libc.so.6:gethostbyname,
uretprobe:/lib64/libc.so.6:gethostbyname2
/@start[tid]/
{
	$latms = (nsecs - @start[tid]) / 1000000;
	time("%H:%M:%S  ");
	printf("%-6d %-16s %6d %s\n", pid, comm, $latms, str(@name[tid]));
	delete(@start[tid]);
	delete(@name[tid]);
}

./bpftrace gethostlatency.bt
Attaching 7 probes...
20:20:52  27757  ping                  1 example.com
```

**Comment by caringi** [comment] 2018-11-21 17:49
Same problem for Fedora...

**Comment by mmarchini** [comment] 2019-01-14 18:05
Would #320 be enough?

**Comment by saurabh83** [comment] 2019-02-20 04:22
@yujinqiu Just curious, how did you get bpftrace to compile on centos. Would appreciate any pointers there.  I am on centos 7.6.

**Comment by yujinqiu** [comment] 2019-02-24 02:09
@mmarchini  that will be great! 👍

**Comment by yujinqiu** [comment] 2019-02-24 05:09
@saurabh83 I use [docker build](https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#using-docker) and copy the  bpftrace static compiled binary to centos.

**Comment by fbs** [comment] 2020-04-07 21:38
Closing this as duplicate of 320

**Closed by fbs** 2020-04-07 21:38 UTC
Labels: tools
