### ISSUE TITLE
15-minutes average is not correct in loads.bt

### ISSUE THREAD

**Issue by ForeverZyh** [iovisor/bpftrace#1611] opened 2020-11-13 01:18 UTC
System: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-53-generic x86_64)
bpftrace version: 0.9.4-1

### What reproduces the bug?
When I run `sudo loads.bt`, the outputs are
```
Attaching 2 probes...
Reading load averages... Hit Ctrl-C to end.
17:43:32 load averages: 0.000 0.000 14.650
17:43:33 load averages: 0.000 0.000 14.650
17:43:34 load averages: 0.000 0.000 14.650
```
The 15-minutes average is not correct because it does not match `uptime`:
```
 17:44:11 up  3:31,  1 user,  load average: 0.00, 0.00, 0.00
```

### bpftrace --info

```
Kernel helpers
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes

Kernel features
  Loop support: yes
```

**Comment by mmisono** [comment] 2020-11-13 02:49
What architecture do you use? if long is 4bytes, then the script should be
```
$load1 = *$avenrun;
$load5 = *($avenrun + 4);
$load15 = *($avenrun + 8);
```

------

(Just realized that `sizeof(long)` does not work.)

**Comment by ForeverZyh** [comment] 2020-11-13 03:47
```
> uname -a
... 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> dpkg --print-architecture 
amd64
```

I think it is 8bytes.

**Comment by mmisono** [comment] 2020-11-13 10:37
Could you try to run the script with `sudo bpftrace -kk loads.bt`? That option reports  runtime errors if any.

**Comment by ForeverZyh** [comment] 2020-11-13 16:02
It seems in my version `0.9.4-1`, the `-kk` option does not exist.

**Comment by ForeverZyh** [comment] 2020-11-13 16:06
I run with `-dd`, hope it helps:
```
Program
 BEGIN
  call: printf
   string: Reading load averages... Hit Ctrl-C to end.\n
 interval:s:1
  =
   variable: $avenrun
   call: kaddr
    string: avenrun
  =
   variable: $load1
   dereference
    variable: $avenrun
  =
   variable: $load5
   dereference
    +
     variable: $avenrun
     int: 8
  =
   variable: $load15
   dereference
    +
     variable: $avenrun
     int: 16
  call: time
   string: %H:%M:%S 
  call: printf
   string: load averages: %d.%03d %d.%03d %d.%03d\n
   >>
    variable: $load1
    int: 11
   >>
    *
     &
      variable: $load1
      -
       <<
        int: 1
        int: 11
       int: 1
     int: 1000
    int: 11
   >>
    variable: $load5
    int: 11
   >>
    *
     &
      variable: $load5
      -
       <<
        int: 1
        int: 11
       int: 1
     int: 1000
    int: 11
   >>
    variable: $load15
    int: 11
   >>
    *
     &
      variable: $load15
      -
       <<
        int: 1
        int: 11
       int: 1
     int: 1000
    int: 11

Before optimization
-------------------

; ModuleID = 'bpftrace'
source_filename = "bpftrace"
target datalayout = "e-m:e-p:64:64-i64:64-n32:64-S128"
target triple = "bpf-pc-linux"

%printf_t = type { i64 }
%printf_t.0 = type { i64, i64, i64, i64, i64, i64, i64 }

; Function Attrs: nounwind
declare i64 @llvm.bpf.pseudo(i64, i64) #0

; Function Attrs: alwaysinline
define internal i64 @log2(i64) #1 section "helpers" {
entry:
  %1 = alloca i64
  %2 = alloca i64
  %3 = bitcast i64* %2 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %3)
  store i64 %0, i64* %2
  %4 = bitcast i64* %1 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %4)
  store i64 0, i64* %1
  %5 = load i64, i64* %2
  %6 = icmp slt i64 %5, 0
  br i1 %6, label %hist.is_less_than_zero, label %hist.is_not_less_than_zero

hist.is_less_than_zero:                           ; preds = %entry
  %7 = load i64, i64* %1
  ret i64 %7

hist.is_not_less_than_zero:                       ; preds = %entry
  %8 = load i64, i64* %2
  %9 = icmp eq i64 %8, 0
  br i1 %9, label %hist.is_zero, label %hist.is_not_zero

hist.is_zero:                                     ; preds = %hist.is_not_less_than_zero
  store i64 1, i64* %1
  %10 = load i64, i64* %1
  ret i64 %10

hist.is_not_zero:                                 ; preds = %hist.is_not_less_than_zero
  store i64 2, i64* %1
  %11 = load i64, i64* %2
  %12 = icmp sge i64 %11, 65536
  %13 = zext i1 %12 to i64
  %14 = shl i64 %13, 4
  %15 = lshr i64 %11, %14
  store i64 %15, i64* %2
  %16 = load i64, i64* %1
  %17 = add i64 %16, %14
  store i64 %17, i64* %1
  %18 = load i64, i64* %2
  %19 = icmp sge i64 %18, 256
  %20 = zext i1 %19 to i64
  %21 = shl i64 %20, 3
  %22 = lshr i64 %18, %21
  store i64 %22, i64* %2
  %23 = load i64, i64* %1
  %24 = add i64 %23, %21
  store i64 %24, i64* %1
  %25 = load i64, i64* %2
  %26 = icmp sge i64 %25, 16
  %27 = zext i1 %26 to i64
  %28 = shl i64 %27, 2
  %29 = lshr i64 %25, %28
  store i64 %29, i64* %2
  %30 = load i64, i64* %1
  %31 = add i64 %30, %28
  store i64 %31, i64* %1
  %32 = load i64, i64* %2
  %33 = icmp sge i64 %32, 4
  %34 = zext i1 %33 to i64
  %35 = shl i64 %34, 1
  %36 = lshr i64 %32, %35
  store i64 %36, i64* %2
  %37 = load i64, i64* %1
  %38 = add i64 %37, %35
  store i64 %38, i64* %1
  %39 = load i64, i64* %2
  %40 = icmp sge i64 %39, 2
  %41 = zext i1 %40 to i64
  %42 = shl i64 %41, 0
  %43 = lshr i64 %39, %42
  store i64 %43, i64* %2
  %44 = load i64, i64* %1
  %45 = add i64 %44, %42
  store i64 %45, i64* %1
  %46 = load i64, i64* %1
  ret i64 %46
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #2

; Function Attrs: alwaysinline
define internal i64 @linear(i64, i64, i64, i64) #1 section "helpers" {
entry:
  %4 = alloca i64
  %5 = alloca i64
  %6 = alloca i64
  %7 = alloca i64
  %8 = alloca i64
  %9 = bitcast i64* %8 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %9)
  %10 = bitcast i64* %7 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %10)
  %11 = bitcast i64* %6 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %11)
  %12 = bitcast i64* %5 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %12)
  %13 = bitcast i64* %4 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %13)
  store i64 %0, i64* %8
  store i64 %1, i64* %7
  store i64 %2, i64* %6
  store i64 %3, i64* %5
  %14 = load i64, i64* %7
  %15 = load i64, i64* %8
  %16 = icmp slt i64 %15, %14
  br i1 %16, label %lhist.lt_min, label %lhist.ge_min

lhist.lt_min:                                     ; preds = %entry
  ret i64 0

lhist.ge_min:                                     ; preds = %entry
  %17 = load i64, i64* %6
  %18 = load i64, i64* %8
  %19 = icmp sgt i64 %18, %17
  br i1 %19, label %lhist.gt_max, label %lhist.le_max

lhist.le_max:                                     ; preds = %lhist.ge_min
  %20 = load i64, i64* %5
  %21 = load i64, i64* %7
  %22 = load i64, i64* %8
  %23 = sub i64 %22, %21
  %24 = udiv i64 %23, %20
  %25 = add i64 %24, 1
  store i64 %25, i64* %4
  %26 = load i64, i64* %4
  ret i64 %26

lhist.gt_max:                                     ; preds = %lhist.ge_min
  %27 = load i64, i64* %5
  %28 = load i64, i64* %7
  %29 = load i64, i64* %6
  %30 = sub i64 %29, %28
  %31 = udiv i64 %30, %27
  %32 = add i64 %31, 1
  store i64 %32, i64* %4
  %33 = load i64, i64* %4
  ret i64 %33
}

define i64 @BEGIN(i8*) section "s_BEGIN_1" {
entry:
  %printf_args = alloca %printf_t
  %1 = bitcast %printf_t* %printf_args to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %1)
  %2 = bitcast %printf_t* %printf_args to i8*
  call void @llvm.memset.p0i8.i64(i8* align 1 %2, i8 0, i64 8, i1 false)
  %3 = getelementptr %printf_t, %printf_t* %printf_args, i32 0, i32 0
  store i64 0, i64* %3
  %pseudo = call i64 @llvm.bpf.pseudo(i64 1, i64 1)
  %get_cpu_id = call i64 inttoptr (i64 8 to i64 ()*)()
  %perf_event_output = call i64 inttoptr (i64 25 to i64 (i8*, i64, i64, %printf_t*, i64)*)(i8* %0, i64 %pseudo, i64 %get_cpu_id, %printf_t* %printf_args, i64 8)
  %4 = bitcast %printf_t* %printf_args to i8*
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* %4)
  ret i64 0
}

; Function Attrs: argmemonly nounwind
declare void @llvm.memset.p0i8.i64(i8* nocapture writeonly, i8, i64, i1 immarg) #2

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #2

define i64 @"interval:s:1"(i8*) section "s_interval:s:1_1" {
entry:
  %printf_args = alloca %printf_t.0
  %perfdata = alloca [16 x i8]
  %"$load15" = alloca i64
  %1 = bitcast i64* %"$load15" to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %1)
  store i64 0, i64* %"$load15"
  %deref3 = alloca i64
  %"$load5" = alloca i64
  %2 = bitcast i64* %"$load5" to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %2)
  store i64 0, i64* %"$load5"
  %deref1 = alloca i64
  %"$load1" = alloca i64
  %3 = bitcast i64* %"$load1" to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %3)
  store i64 0, i64* %"$load1"
  %deref = alloca i64
  %"$avenrun" = alloca i64
  %4 = bitcast i64* %"$avenrun" to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %4)
  store i64 0, i64* %"$avenrun"
  %5 = bitcast i64* %"$avenrun" to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %5)
  store i64 -1816587360, i64* %"$avenrun"
  %6 = load i64, i64* %"$avenrun"
  %7 = bitcast i64* %deref to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %7)
  %probe_read = call i64 inttoptr (i64 4 to i64 (i8*, i64, i8*)*)(i64* %deref, i64 8, i64 %6)
  %8 = load i64, i64* %deref
  %9 = bitcast i64* %deref to i8*
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* %9)
  %10 = bitcast i64* %"$load1" to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %10)
  store i64 %8, i64* %"$load1"
  %11 = load i64, i64* %"$avenrun"
  %12 = add i64 %11, 8
  %13 = bitcast i64* %deref1 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %13)
  %probe_read2 = call i64 inttoptr (i64 4 to i64 (i8*, i64, i8*)*)(i64* %deref1, i64 8, i64 %12)
  %14 = load i64, i64* %deref1
  %15 = bitcast i64* %deref1 to i8*
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* %15)
  %16 = bitcast i64* %"$load5" to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %16)
  store i64 %14, i64* %"$load5"
  %17 = load i64, i64* %"$avenrun"
  %18 = add i64 %17, 16
  %19 = bitcast i64* %deref3 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %19)
  %probe_read4 = call i64 inttoptr (i64 4 to i64 (i8*, i64, i8*)*)(i64* %deref3, i64 8, i64 %18)
  %20 = load i64, i64* %deref3
  %21 = bitcast i64* %deref3 to i8*
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* %21)
  %22 = bitcast i64* %"$load15" to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %22)
  store i64 %20, i64* %"$load15"
  %23 = bitcast [16 x i8]* %perfdata to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %23)
  store i64 30004, [16 x i8]* %perfdata
  %24 = getelementptr [16 x i8], [16 x i8]* %perfdata, i64 0, i64 8
  store i64 0, i8* %24
  %pseudo = call i64 @llvm.bpf.pseudo(i64 1, i64 1)
  %get_cpu_id = call i64 inttoptr (i64 8 to i64 ()*)()
  %perf_event_output = call i64 inttoptr (i64 25 to i64 (i8*, i64, i64, [16 x i8]*, i64)*)(i8* %0, i64 %pseudo, i64 %get_cpu_id, [16 x i8]* %perfdata, i64 16)
  %25 = bitcast [16 x i8]* %perfdata to i8*
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* %25)
  %26 = bitcast %printf_t.0* %printf_args to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* %26)
  %27 = bitcast %printf_t.0* %printf_args to i8*
  call void @llvm.memset.p0i8.i64(i8* align 1 %27, i8 0, i64 56, i1 false)
  %28 = getelementptr %printf_t.0, %printf_t.0* %printf_args, i32 0, i32 0
  store i64 1, i64* %28
  %29 = load i64, i64* %"$load1"
  %30 = lshr i64 %29, 11
  %31 = getelementptr %printf_t.0, %printf_t.0* %printf_args, i32 0, i32 1
  store i64 %30, i64* %31
  %32 = load i64, i64* %"$load1"
  %33 = and i64 %32, 2047
  %34 = mul i64 %33, 1000
  %35 = lshr i64 %34, 11
  %36 = getelementptr %printf_t.0, %printf_t.0* %printf_args, i32 0, i32 2
  store i64 %35, i64* %36
  %37 = load i64, i64* %"$load5"
  %38 = lshr i64 %37, 11
  %39 = getelementptr %printf_t.0, %printf_t.0* %printf_args, i32 0, i32 3
  store i64 %38, i64* %39
  %40 = load i64, i64* %"$load5"
  %41 = and i64 %40, 2047
  %42 = mul i64 %41, 1000
  %43 = lshr i64 %42, 11
  %44 = getelementptr %printf_t.0, %printf_t.0* %printf_args, i32 0, i32 4
  store i64 %43, i64* %44
  %45 = load i64, i64* %"$load15"
  %46 = lshr i64 %45, 11
  %47 = getelementptr %printf_t.0, %printf_t.0* %printf_args, i32 0, i32 5
  store i64 %46, i64* %47
  %48 = load i64, i64* %"$load15"
  %49 = and i64 %48, 2047
  %50 = mul i64 %49, 1000
  %51 = lshr i64 %50, 11
  %52 = getelementptr %printf_t.0, %printf_t.0* %printf_args, i32 0, i32 6
  store i64 %51, i64* %52
  %pseudo5 = call i64 @llvm.bpf.pseudo(i64 1, i64 1)
  %get_cpu_id6 = call i64 inttoptr (i64 8 to i64 ()*)()
  %perf_event_output7 = call i64 inttoptr (i64 25 to i64 (i8*, i64, i64, %printf_t.0*, i64)*)(i8* %0, i64 %pseudo5, i64 %get_cpu_id6, %printf_t.0* %printf_args, i64 56)
  %53 = bitcast %printf_t.0* %printf_args to i8*
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* %53)
  ret i64 0
}

attributes #0 = { nounwind }
attributes #1 = { alwaysinline }
attributes #2 = { argmemonly nounwind }

After optimization
------------------

; ModuleID = 'bpftrace'
source_filename = "bpftrace"
target datalayout = "e-m:e-p:64:64-i64:64-n32:64-S128"
target triple = "bpf-pc-linux"

%printf_t = type { i64 }
%printf_t.0 = type { i64, i64, i64, i64, i64, i64, i64 }

; Function Attrs: nounwind
declare i64 @llvm.bpf.pseudo(i64, i64) #0

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #1

define i64 @BEGIN(i8*) local_unnamed_addr section "s_BEGIN_1" {
entry:
  %printf_args = alloca %printf_t, align 8
  %1 = bitcast %printf_t* %printf_args to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* nonnull %1)
  %2 = getelementptr inbounds %printf_t, %printf_t* %printf_args, i64 0, i32 0
  store i64 0, i64* %2, align 8
  %pseudo = tail call i64 @llvm.bpf.pseudo(i64 1, i64 1)
  %get_cpu_id = tail call i64 inttoptr (i64 8 to i64 ()*)()
  %perf_event_output = call i64 inttoptr (i64 25 to i64 (i8*, i64, i64, %printf_t*, i64)*)(i8* %0, i64 %pseudo, i64 %get_cpu_id, %printf_t* nonnull %printf_args, i64 8)
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* nonnull %1)
  ret i64 0
}

; Function Attrs: argmemonly nounwind
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #1

define i64 @"interval:s:1"(i8*) local_unnamed_addr section "s_interval:s:1_1" {
entry:
  %printf_args = alloca %printf_t.0, align 8
  %perfdata = alloca [16 x i8], align 8
  %deref3 = alloca i64, align 8
  %deref1 = alloca i64, align 8
  %deref = alloca i64, align 8
  %1 = bitcast i64* %deref to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* nonnull %1)
  %probe_read = call i64 inttoptr (i64 4 to i64 (i8*, i64, i8*)*)(i64* nonnull %deref, i64 8, i64 -1816587360)
  %2 = load i64, i64* %deref, align 8
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* nonnull %1)
  %3 = bitcast i64* %deref1 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* nonnull %3)
  %probe_read2 = call i64 inttoptr (i64 4 to i64 (i8*, i64, i8*)*)(i64* nonnull %deref1, i64 8, i64 -1816587352)
  %4 = load i64, i64* %deref1, align 8
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* nonnull %3)
  %5 = bitcast i64* %deref3 to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* nonnull %5)
  %probe_read4 = call i64 inttoptr (i64 4 to i64 (i8*, i64, i8*)*)(i64* nonnull %deref3, i64 8, i64 -1816587344)
  %6 = load i64, i64* %deref3, align 8
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* nonnull %5)
  %7 = getelementptr inbounds [16 x i8], [16 x i8]* %perfdata, i64 0, i64 0
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* nonnull %7)
  store i64 30004, [16 x i8]* %perfdata, align 8
  %8 = getelementptr inbounds [16 x i8], [16 x i8]* %perfdata, i64 0, i64 8
  store i64 0, i8* %8, align 8
  %pseudo = call i64 @llvm.bpf.pseudo(i64 1, i64 1)
  %get_cpu_id = call i64 inttoptr (i64 8 to i64 ()*)()
  %perf_event_output = call i64 inttoptr (i64 25 to i64 (i8*, i64, i64, [16 x i8]*, i64)*)(i8* %0, i64 %pseudo, i64 %get_cpu_id, [16 x i8]* nonnull %perfdata, i64 16)
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* nonnull %7)
  %9 = bitcast %printf_t.0* %printf_args to i8*
  call void @llvm.lifetime.start.p0i8(i64 -1, i8* nonnull %9)
  %10 = getelementptr inbounds %printf_t.0, %printf_t.0* %printf_args, i64 0, i32 0
  store i64 1, i64* %10, align 8
  %11 = lshr i64 %2, 11
  %12 = getelementptr inbounds %printf_t.0, %printf_t.0* %printf_args, i64 0, i32 1
  store i64 %11, i64* %12, align 8
  %13 = and i64 %2, 2047
  %14 = mul nuw nsw i64 %13, 1000
  %15 = lshr i64 %14, 11
  %16 = getelementptr inbounds %printf_t.0, %printf_t.0* %printf_args, i64 0, i32 2
  store i64 %15, i64* %16, align 8
  %17 = lshr i64 %4, 11
  %18 = getelementptr inbounds %printf_t.0, %printf_t.0* %printf_args, i64 0, i32 3
  store i64 %17, i64* %18, align 8
  %19 = and i64 %4, 2047
  %20 = mul nuw nsw i64 %19, 1000
  %21 = lshr i64 %20, 11
  %22 = getelementptr inbounds %printf_t.0, %printf_t.0* %printf_args, i64 0, i32 4
  store i64 %21, i64* %22, align 8
  %23 = lshr i64 %6, 11
  %24 = getelementptr inbounds %printf_t.0, %printf_t.0* %printf_args, i64 0, i32 5
  store i64 %23, i64* %24, align 8
  %25 = and i64 %6, 2047
  %26 = mul nuw nsw i64 %25, 1000
  %27 = lshr i64 %26, 11
  %28 = getelementptr inbounds %printf_t.0, %printf_t.0* %printf_args, i64 0, i32 6
  store i64 %27, i64* %28, align 8
  %pseudo5 = call i64 @llvm.bpf.pseudo(i64 1, i64 1)
  %get_cpu_id6 = call i64 inttoptr (i64 8 to i64 ()*)()
  %perf_event_output7 = call i64 inttoptr (i64 25 to i64 (i8*, i64, i64, %printf_t.0*, i64)*)(i8* %0, i64 %pseudo5, i64 %get_cpu_id6, %printf_t.0* nonnull %printf_args, i64 56)
  call void @llvm.lifetime.end.p0i8(i64 -1, i8* nonnull %9)
  ret i64 0
}

attributes #0 = { nounwind }
attributes #1 = { argmemonly nounwind }
```

**Comment by mmisono** [comment] 2020-11-13 20:03
This seems a culprit.
```
  store i64 30004, [16 x i8]* %perfdata, align 8
```

```c
% cat a.c
#include <stdio.h>

int main(){
    long a = 30004;
    long b = (a >> 11);
    long c = ((a & ((1 << 11) - 1)) * 1000) >> 11;

    printf("%ld.%03ld\n", b, c);

    return 0;
}
```

```sh
% ./a.out
14.650
```

..... so, this problem is #1305. We are trying to fix that, but the problem is not fixed yet (on master). There is no easy workaround. I recommend you to upgrade bpftrace that supports `-k` option and try to use it (i.e., `bpftrace -k loads.bt`).
Sometimes `-k` options solve the problem since it inserts some BPF code, and as a result program structure will change.

**Comment by berndfinger** [comment] 2021-06-30 07:56
Just encountered the same problem, using bpftrace v0.9.2 on RHEL 8.2. Interestingly, I can solve the problem by adding one more (otherwise superfluous) line of variable assignment, like in the following example:
    	$load1 = *$avenrun;
    	$load5 = *($avenrun + 8);
    	$load15 = *($avenrun + 16);
    	$load16 = *($avenrun + 16);
The printf line remains the same as before and is now printing the correct values (compared to uptime or w outputs).

**Comment by danobi** [comment] 2021-06-30 19:10
@berndfinger yep, that sounds like the llvm < 12 miscompiles.

**Comment by viktormalik** [comment] 2023-01-06 10:21
Since #1305 is now closed, closing this, too.

**Closed by viktormalik** 2023-01-06 10:21 UTC
Labels: bug
