### ISSUE TITLE
Unable to use gethostlatency.bt on NixOs

### ISSUE THREAD

**Issue by FlakM** [iovisor/bpftrace#2813] opened 2023-10-27 10:37 UTC
### What reproduces the bug? Provide code if possible.

```bash
❯ sudo gethostlatency.bt
/run/current-system/sw/bin/gethostlatency.bt:27-29: ERROR: uprobe target file 'libc' does not exist or is not executable
/run/current-system/sw/bin/gethostlatency.bt:29-30: ERROR: uprobe target file 'libc' does not exist or is not executable
/run/current-system/sw/bin/gethostlatency.bt:30-31: ERROR: uprobe target file 'libc' does not exist or is not executable
/run/current-system/sw/bin/gethostlatency.bt:35-37: ERROR: uprobe target file 'libc' does not exist or is not executable
/run/current-system/sw/bin/gethostlatency.bt:37-38: ERROR: uprobe target file 'libc' does not exist or is not executable
/run/current-system/sw/bin/gethostlatency.bt:38-39: ERROR: uprobe target file 'libc' does not exist or is not executable
❯ sudo bpftrace -l 'uprobe:libc:*'
stdin:1:1-14: ERROR: uprobe target file 'libc' does not exist or is not executable
uprobe:libc:*
~~~~~~~~~~~~~
```

Meanwhile if i specify pid the bcc gethostlatency works fine:

```bash
❯ sudo gethostlatency -p $(pgrep firefox)
TIME      PID     COMM                  LATms HOST
12:34:49  7393    DNS Res~ver #23       10.64 www.google.com
```

### `bpftrace --info` output

```bash
❯ sudo bpftrace --info
System
  OS: Linux 6.1.57 #1-NixOS SMP PREEMPT_DYNAMIC Tue Oct 10 20:00:46 UTC 2023
  Arch: x86_64

Build
  version: v0.19.1
  LLVM: 16.0.6
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: yes
  get_func_ip: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: no
  raw_tp_special: yes
  iter: yes
```

Also thank you very much for all of your work! <3

**Comment by viktormalik** [comment] 2023-10-30 12:02
This looks like a NixOS problem rather than a bpftrace problem to me.

The `:libc` target should be automatically resolved to the path to the libc shared library. bpftrace does that using BCC's [bcc_procutils_which_so](https://github.com/iovisor/bcc/blob/master/src/cc/bcc_proc.c#L508) which tries to find the path in `/etc/ld.so.cache`. Perhaps that file is not available on NixOS? It's strange, though, that BCC is able to resolve the path, perhaps they use additional tricks to find the path.

FWIW, you can fix the issue by manually overriding the `:libc` parts of probes by a path to the libc shared library in `gethostlatency.bt` (would be `:/usr/lib64/libc.so.6` on more traditional systems). Other than that, we'd probably need some NixOS expert to propose a better solution.

**Comment by FlakM** [comment] 2023-10-31 08:11
Thanks for the response @viktormalik! Unlike on regular distribution on my system there are multiple versions of glibc. Could this be the reason behind why this might never work?

At the same time [which_so_in_process](https://github.com/iovisor/bcc/blob/master/src/cc/bcc_proc.c#L468) finds a specific so that binary links to and everything works fine :thinking:

**Comment by viktormalik** [comment] 2023-10-31 08:31
> At the same time [which_so_in_process](https://github.com/iovisor/bcc/blob/master/src/cc/bcc_proc.c#L468) finds a specific so that binary links to and everything works fine 🤔

Ah, right, so that's the reason. The bpftrace version of gethostlatency doesn't have an option to pass a PID so `which_so_in_process` never gets called.

Could you try this?
```
$ sudo bpftrace $(which gethostlatency.bt) -p $(pgrep firefox)
```

**Comment by FlakM** [comment] 2023-10-31 08:44
It works but catches all calls - not limited to the the firefox process. Is this the expected behavior?

**Comment by viktormalik** [comment] 2023-10-31 10:54
Not really, gethostlatency uses uprobes and those have an option to specify a PID during attachment. I could have a look but I'm not very familiar with NixOS, do you have a simple reproducer that I could run, e.g., in a container or VM? Or simply with Nix?

**Comment by FlakM** [comment] 2023-10-31 13:07
Of course! Here is the reproducer repository: https://github.com/FlakM/trace_repro 

it requires curl and piping some stuff into shell to install nix and qemu setup on host machine :see_no_evil:

![image](https://github.com/iovisor/bpftrace/assets/4190088/21327d91-0e02-4533-bc04-01a46d0ce1bb)

**Comment by viktormalik** [comment] 2023-10-31 16:33
That's what I call a repro, thanks!

Anyways, it turned out that I was wrong - we're not passing PID during uprobe attachment (at least not the PID given on CLI), so what you observe is really the expected behaviour. I tried to put down a quick fix but it didn't work, so I'll need to investigate this more and then I'll follow-up with creating a new issue to track this as a missing feature.

**Comment by viktormalik** [comment] 2023-11-01 07:11
Closing this in favor of #2817.

@FlakM feel free to reopen if necessary.

**Closed by viktormalik** 2023-11-01 07:11 UTC
Labels: bug

**Comment by FlakM** [comment] 2023-11-07 11:14
It's funny that the same tool that made reproducing easy caused the problem in a first place. Thank you for the support!
