### ISSUE TITLE
tcpconnect.bt prints weird destination port

### ISSUE THREAD

**Issue by rhdxmr** [iovisor/bpftrace#1332] opened 2020-05-15 06:42 UTC
Hi,

I am using Pop!_OS 20.04
```
03:05:52 15 ❯  lsb_release  -a
No LSB modules are available.
Distributor ID: Pop
Description:    Pop!_OS 20.04 LTS
Release:        20.04
Codename:       focal
```

kernel version is 5.4.0

```
03:08:54 15 ❯  uname -a
Linux pop-os 5.4.0-7626-generic #30~1588169883~20.04~bbe668a-Ubuntu SMP Wed Apr 29 21:00:02 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

I installed bpftrace by apt.

```
sudo apt install bpftrace
```

But tcpconnect.bt prints weird destination port.

At a terminal, run curl to get google.com:80

And at another terminal, run tcpconnect.bt
```

03:04:10 15 ❯  /usr/bin/bpftrace /sbin/tcpconnect.bt
Attaching 2 probes...
Tracing tcp connections. Hit Ctrl-C to end.
TIME     PID      COMM             SADDR                                   SPORT  DADDR                                   DPORT
15:04:13 980915   curl             192.168.0.9                             60490  172.217.175.14                          13429
^C
```

DPORT shows 13429, not 80.

bpftrace depends on LLVM 9.
Maybe is it a reason of this problem?

```
03:04:15 15 ❯  apt depends bpftrace
bpftrace
  Depends: libbpfcc (>= 0.12.0)
  Depends: libc6 (>= 2.27)
  Depends: libclang1-9 (>= 1:9~svn359771-1~)
  Depends: libgcc-s1 (>= 3.0)
  Depends: libllvm9 (>= 1:9~svn298832-1~)

```

INSTALL.md suggests to use LLVM 7.

So I built bpftrace from source with LLVM 7. And tcpconnect.bt works as expected. yay

```
03:11:44 15 ❯  ldd /home/esrse/.local/bin/bpftrace
        linux-vdso.so.1 (0x00007ffd2757f000)
        libbfd-2.34-system.so => /lib/x86_64-linux-gnu/libbfd-2.34-system.so (0x00007f661a382000)
        libopcodes-2.34-system.so => /lib/x86_64-linux-gnu/libopcodes-2.34-system.so (0x00007f661a224000)
        libbcc.so.0 => /lib/x86_64-linux-gnu/libbcc.so.0 (0x00007f6616878000)
        libclang-7.so.1 => /lib/x86_64-linux-gnu/libclang-7.so.1 (0x00007f661502c000)
        libLLVM-7.so.1 => /lib/x86_64-linux-gnu/libLLVM-7.so.1 (0x00007f6611769000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6611588000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f661156b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6611379000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f661135d000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6611357000)
        libelf.so.1 => /lib/x86_64-linux-gnu/libelf.so.1 (0x00007f661133b000)
        libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f661130b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f66112e6000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6611197000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f661a639000)
        libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007f661118b000)
        libedit.so.2 => /lib/x86_64-linux-gnu/libedit.so.2 (0x00007f6611153000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6611148000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f661112c000)

```

But if I build bpftrace from source with LLVM 9, the build process succeeds but tcpconnect.bt prints weird destination port again. oops

```
03:19:09 15 ❯  ldd /home/esrse/.local/bin/bpftrace
        linux-vdso.so.1 (0x00007ffe8de3c000)
        libbfd-2.34-system.so => /lib/x86_64-linux-gnu/libbfd-2.34-system.so (0x00007f8628173000)
        libopcodes-2.34-system.so => /lib/x86_64-linux-gnu/libopcodes-2.34-system.so (0x00007f8628015000)
        libbcc.so.0 => /lib/x86_64-linux-gnu/libbcc.so.0 (0x00007f8624669000)
        libclang-9.so.1 => /lib/x86_64-linux-gnu/libclang-9.so.1 (0x00007f862294b000)
        libLLVM-9.so.1 => /lib/x86_64-linux-gnu/libLLVM-9.so.1 (0x00007f861e6fc000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f861e51b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f861e4fe000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f861e30c000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f861e2f0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f861e2ea000)
        libelf.so.1 => /lib/x86_64-linux-gnu/libelf.so.1 (0x00007f861e2ce000)
        libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007f861e29e000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f861e279000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f861e12a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f862842b000)
        libffi.so.7 => /lib/x86_64-linux-gnu/libffi.so.7 (0x00007f861e11e000)
        libedit.so.2 => /lib/x86_64-linux-gnu/libedit.so.2 (0x00007f861e0e6000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f861e0db000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f861e0bf000)
```

When I modify tcpconnect.bt as shown below, destination port column prints correct number.

```
kprobe:tcp_connect
{
  $sk = ((struct sock *) arg0);
  $inet_family = $sk->__sk_common.skc_family;

  if ($inet_family == AF_INET || $inet_family == AF_INET6) {
    if ($inet_family == AF_INET) {
      $daddr = ntop($sk->__sk_common.skc_daddr);
      $saddr = ntop($sk->__sk_common.skc_rcv_saddr);
    } else {
      $daddr = ntop($sk->__sk_common.skc_v6_daddr.in6_u.u6_addr8);
      $saddr = ntop($sk->__sk_common.skc_v6_rcv_saddr.in6_u.u6_addr8);
    }
    $lport = $sk->__sk_common.skc_num;
    $dport = $sk->__sk_common.skc_dport;
    $last_var = $sk->__sk_common.skc_dport;  // this line is added

    // Destination port is big endian, it must be flipped
    $dport = ($dport >> 8) | (($dport << 8) & 0x00FF00);

    time("%H:%M:%S ");
    printf("%-8d %-16s ", pid, comm);
    printf("%-39s %-6d %-39s %-6d\n", $saddr, $lport, $daddr, $dport);
  }
}
```

Why does this happen?

I hope to dig into it more but I do not have enough background of BPF, so I gave up.

Could you have a look at this problem and find a reason?

Anyway, now I am OK with bpftrace built with LLVM 7.

**Comment by rhdxmr** [comment] 2020-05-15 07:45
Let me know if you need more info from me.

**Comment by mmisono** [comment] 2020-05-15 08:35
I reproduced this using master built with LLVM10. I also found that the LLVM8 build did not have the problem. The generated code are (left: llvm10, right: llvm8):

![image](https://user-images.githubusercontent.com/186170/82028731-fa9a4680-96d0-11ea-8f8f-8f10312427cf.png)

Here, `bpf_probe_read()` reads `$sk->__sk_common.skc_dport` and stores the result in `r10-72`. However, the LLVM10 code overwrites the result with 30004 (note that ntoh(30004) = 13429).

> 97: (85) call bpf_probe_read#4
> 98: (b7) r1 = 30004
> 99: (7b) *(u64 *)(r10 -72) = r1

This is similar to what I found in https://github.com/iovisor/bpftrace/issues/1305#issuecomment-618806972. I wonder if recent LLVM backends have some problems.

**Comment by rhdxmr** [comment] 2020-05-27 06:44
Hello @mmisono,
Is there progress in this issue?
Why does LLVM 9+ generate invalid BPF bytecode?

**Comment by mmisono** [comment] 2020-05-27 07:55
I'm not sure but #873 might be related (@fbs is fixing it).

**Comment by fbs** [comment] 2020-05-27 08:41
I think it is related too, the handling of smaller ints needs  to be improved. I am working on it but its not going as quick as i hoped. Hope to have an update soon :)

**Comment by ema** [comment] 2020-11-30 09:27
> When I modify tcpconnect.bt as shown below, destination port column prints correct number.
[...]
>     $last_var = $sk->__sk_common.skc_dport;  // this line is added

Note that this workaround only works with dports such as 22 and 80, while it does not for 443 (among others).

It also looks like the issue is affecting `kprobe:tcp_connect`, but not others such as for instance `kprobe:tcp_ack` and `kprobe:tcp_send_ack`. The following script prints the right values for **$dport**:

```
#include <net/sock.h>

kprobe:tcp_send_ack {
  $sk = ((struct sock *) arg0);
  $inet_family = $sk->__sk_common.skc_family;

  if ($inet_family == AF_INET) {
    $daddr = ntop($sk->__sk_common.skc_daddr);
    $saddr = ntop($sk->__sk_common.skc_rcv_saddr);
  } else {
    $daddr = ntop($sk->__sk_common.skc_v6_daddr.in6_u.u6_addr8);
    $saddr = ntop($sk->__sk_common.skc_v6_rcv_saddr.in6_u.u6_addr8);
  }
  $lport = $sk->__sk_common.skc_num;
  $dport = $sk->__sk_common.skc_dport;

  // Destination port is big endian, it must be flipped
  $dport = ($dport >> 8) | (($dport << 8) & 0x00FF00);

  printf("%-39s %-6d %-39s %-6d\n", $saddr, $lport, $daddr, $dport);
}
```

**Comment by mmisono** [comment] 2020-11-30 11:12
This is an LLVM bug: https://github.com/iovisor/bpftrace/issues/1305#issuecomment-695926521
and I'm not sure the exact condition to reproduce this bug...

**Comment by ema** [comment] 2020-11-30 13:48
> This is an LLVM bug: [#1305 (comment)](https://github.com/iovisor/bpftrace/issues/1305#issuecomment-695926521)
> and I'm not sure the exact condition to reproduce this bug...

In case it helps narrowing down the LLVM issue, it seems that there are at least two ways to reproduce the bug. The first is
related to printf. Remove the `printf("");` statement to get the right port number:

```
#include <net/sock.h>

kprobe:tcp_connect
{
  $sk = ((struct sock *) arg0);
  $dport = $sk->__sk_common.skc_dport;
  $dport = ($dport >> 8) | (($dport << 8) & 0x00FF00);
  // dport is correct if the following printf() is commented, 0 otherwise
  printf("");
  printf("%d\n", $dport)
}
```

The second has to do with conditionals. Remove the `if ($inet_family != 42)` statement to get the right port number:

```
#include <net/sock.h>

kprobe:tcp_connect
{
  $sk = ((struct sock *) arg0);
  $inet_family = $sk->__sk_common.skc_family;

  if ($inet_family != 42) {
    $dport = $sk->__sk_common.skc_dport;
    $dport = ($dport >> 8) | (($dport << 8) & 0x00FF00);
    printf("%d\n", $dport)
  }
}
```

**Comment by danobi** [comment] 2020-11-30 19:20
@ema thanks for investigating. As I understand it, the llvm bug has to do with lifetimes and stack reuse. So it's possible that by adding / removing other bits of code you can trigger the bug (or work around it). This is a pretty nasty bug.

**Comment by mmisono** [comment] 2023-01-06 15:25
I believe #1305 (using llvm >= 12)  solves this problem. Closing this.

**Closed by mmisono** 2023-01-06 15:25 UTC
Labels: bug

**Comment by ema** [comment] 2023-01-06 15:43
Confirmed, all good now with llvm 14. Thank you @mmisono!
